create or replace package migration.pk_produits as

FUNCTION CreationDepot(
  ADEPOT IN VARCHAR2,
  ALIBELLE IN VARCHAR2,
  AAUTOMATE IN NUMBER,
  T_Depot_ID OUT NUMBER
 )RETURN NUMBER;

FUNCTION CreationZoneGeo(
  AZoneGeo IN VARCHAR2,
  ALibelle IN VARCHAR2,
  T_zonegeo_ID OUT NUMBER
  ) RETURN NUMBER;
  
FUNCTION CreationProduit(
  APRODUIT IN VARCHAR2,
  ACODECNK IN VARCHAR2,
  ADESIGNATION IN VARCHAR2,
  ADESIGNATIONNL IN VARCHAR2,
  AAVEC_CBU IN VARCHAR2,
  AGEREINTERESSEMENT IN VARCHAR2,
  ACOMMENTAIREVENTE IN VARCHAR2,
  AGERESUIVICLIENT IN VARCHAR2,
  ATRACABILITE IN VARCHAR2,
  APROFILGS IN VARCHAR2,
  ACALCULGS IN VARCHAR2,
  AVETERINAIRE IN VARCHAR2,
  AVIDEO IN VARCHAR2,
  ADESIGNATIONLIBREPOSSIBLE IN VARCHAR2,
  AFRIGO IN VARCHAR2,
  APEREMPTIONCOURTE IN VARCHAR2,
  ACATPROD IN VARCHAR2,
  ASTATUTCOMMERC IN VARCHAR2,
  AUSAGEPROD IN VARCHAR2,
  AREMISEINTERDITE IN VARCHAR2,
  ARISTOURNEINTERDITE IN VARCHAR2,
  APDTPROPRE IN VARCHAR2,
    ATVA IN NUMBER,
    APRIXVENTE IN NUMBER,
    APRIXACHATCATALOGUE    IN NUMBER,
    ALABO IN VARCHAR2,
    ACONCESS IN VARCHAR2,
    ASTOCKMINI IN NUMBER,
  ASTOCKMAXI IN NUMBER,
  ADATEDERNDELIV IN DATE,
  ADATEPEREMPTION IN DATE,
  AZONELIBRE IN VARCHAR2,
  ATAUXREMISE IN NUMBER,
  ATAUXRIST IN NUMBER,
  AVENTILATION IN VARCHAR2,
  ACREATIONLGCMD IN VARCHAR2,
  ACLASSIFINT IN NUMBER, 
  ATYPEPRIXBLOQUE IN NUMBER,
  ADESIGNATIONBLOQUEE IN VARCHAR2,
  AFICHEBLOQUEE IN VARCHAR2,
  AFUSION IN CHAR
 ) RETURN NUMBER;

FUNCTION CreationProduitGeographique(
  AStock IN VARCHAR2,
  AStockQuantite IN NUMBER,
  AStockMini IN NUMBER,
  AStockMaxi IN NUMBER,
  /* AStockQtePromise IN NUMBER, */
  ADepot IN VARCHAR2,
  AZoneGeo IN VARCHAR2,
  AProduit IN VARCHAR2,
  APriorite IN VARCHAR2,
  ADepotVente IN VARCHAR2,
  AFUSION IN CHAR
 ) RETURN NUMBER;
 
FUNCTION CreationRepartiteur(
  ARepartiteur IN VARCHAR2,
  ANomRepart IN VARCHAR2,
  ARue1 IN VARCHAR2,
  ARue2 IN VARCHAR2,
  ACodePostal IN VARCHAR2,
  ANomVille IN VARCHAR2,
  --ACodePays in varchar2,
  ATelPersonnel IN VARCHAR2,
  ATelStandard IN VARCHAR2,
  ATelMobile IN VARCHAR2,
  AEmail IN VARCHAR2,
  AFax IN VARCHAR2,
  AVitesse IN NUMBER,
  APause IN VARCHAR2,
  ANbTentatives IN NUMBER,
  ARepDefaut IN VARCHAR2,
  AObjCAMensuel IN NUMBER,
  AModeTransmission IN VARCHAR2,
  T_Repartiteur_ID OUT NUMBER
)RETURN NUMBER;

FUNCTION CreationFournisseur(
  AFournisseur IN VARCHAR2,
  ANomFourn IN VARCHAR2,
  ARue1 IN VARCHAR2,
  ARue2 IN VARCHAR2,
  ACodePostal IN VARCHAR2,
  ANomVille IN VARCHAR2,
--  ACodePays in varchar2,
  ATelPersonnel IN VARCHAR2,
  ATelStandard IN VARCHAR2,
  ATelMobile IN VARCHAR2,
  AEmail IN VARCHAR2,
  AFax IN VARCHAR2,
  AVitesse IN NUMBER,
  APause IN VARCHAR2,
  ANbTentatives IN NUMBER,
  AModeTransmission IN VARCHAR2,
  AFouPartenaire IN VARCHAR2,
  AMonoGamme IN VARCHAR2,
  T_FOURNISSEUR_ID OUT NUMBER
) RETURN NUMBER;

FUNCTION CreationPdtFournisseur(
  APdtFournisseur IN VARCHAR2,
  AProduit IN NUMBER,
  AFournisseur IN NUMBER,
  APriorite IN NUMBER,
  APrixAchat IN NUMBER,
  ARemise IN NUMBER,
  APrixARemise IN NUMBER,
  AGereOffiCentral IN VARCHAR2,
  T_PDTFOURNISSEUR_ID OUT NUMBER
 ) RETURN NUMBER;

FUNCTION CreationCodeBarre(
    ACodeBarre IN VARCHAR2,
    AProduit IN NUMBER,
    ACode IN VARCHAR2,
    AEan13 IN VARCHAR2,
    ACbu IN VARCHAR2,
  T_CODEBARRE_ID OUT NUMBER
  ) RETURN NUMBER;

FUNCTION CreationFicheAnalyse(
   Afiche_analyse_id IN VARCHAR2
  ,Acnk_produit IN VARCHAR2
  ,Ano_analyse IN  VARCHAR2
  ,Ano_autorisation IN VARCHAR2
  ,ATR_ReferenceAnalytique IN NUMBER
  ,Adate_entree IN DATE
  ,Afabricant_id IN VARCHAR2
  ,Agrossiste_id IN VARCHAR2
  ,Ano_lot IN VARCHAR2
  ,Aprix_achat IN NUMBER
  ,Acnk_lie IN VARCHAR2
  ,Ano_bon_livraison IN VARCHAR2
  ,Adate_ouverture IN DATE
  ,Adate_peremption IN DATE
  ,Adate_fermeture IN DATE
  ,Aetat IN NUMBER
  ,Aquantite_initial IN NUMBER
  ,Aunite_qte IN VARCHAR2  
  ,Aquantite_restante IN NUMBER
  ,Aremarques IN VARCHAR2
  ,Adatemaj IN DATE
  ,Azonegeo_id IN VARCHAR2
  ,T_chim_ficheana_ID OUT NUMBER
) RETURN NUMBER;

FUNCTION CreationFormulaire(
     Aformulaire_id IN VARCHAR2
	,Alibelle_FR IN VARCHAR2
	,Alibelle_NL IN VARCHAR2
	,Anom_court_FR IN VARCHAR2
	,Anom_court_NL IN VARCHAR2
	,Atype_formulaire IN NUMBER
	,T_FORMULAIRE_ID OUT NUMBER
) RETURN NUMBER;

FUNCTION CreationFormule(
	Aformule_id IN VARCHAR2
	,Aformulaire_id IN VARCHAR2
	,AFORMULE_UID IN NUMBER
	,Acnk IN VARCHAR2
	,Alibelle_FR IN VARCHAR2
	,Alibelle_NL IN VARCHAR2
	,ATYPE_FORME_GALENIQUE IN NUMBER
	,AQUANTITEPREPAREE IN NUMBER
	,AUNITEQUANTITE IN NUMBER
	,ACOMMENTAIRE IN VARCHAR2
	,AETAT IN VARCHAR2
	,ADATEMAJ IN DATE
	,T_FORMULE_ID OUT NUMBER
) RETURN NUMBER;

FUNCTION CreationFormuleLigne(
	AFORMULE_LIGNE_ID IN VARCHAR2
	,AFORMULE_ID IN NUMBER
	,AORDRE IN NUMBER
	,ACHIM_PRODUIT_CNK IN VARCHAR2
	,APRODUIT_ID IN NUMBER
	,AFORMULE_INCORPOREE_ID IN NUMBER
	,AUNITEQUANTITE IN NUMBER
	,AQUANTITE IN NUMBER
	,AMENTION_COMPLEMENTAIRE IN VARCHAR2
	,ADATEMAJ IN DATE
	,T_FORMULE_LIGNE_ID OUT NUMBER
) RETURN NUMBER;

end;
/