git rm --cached Composants/AccesBD/zeosdbo/packages/Delphi2010/ZPlain.drc
git rm --cached Composants/Librairies/jwa/Win32API/JwaLmApiBuf.dcu
git rm --cached Composants/Librairies/jwa/Win32API/JwaLmCons.dcu
git rm --cached Composants/Librairies/jwa/Win32API/JwaLmErr.dcu
git rm --cached Composants/Librairies/jwa/Win32API/JwaLmServer.dcu
git rm --cached Composants/Librairies/jwa/Win32API/JwaNtStatus.dcu
git rm --cached Composants/Librairies/jwa/Win32API/JwaWinBase.dcu
git rm --cached Composants/Librairies/jwa/Win32API/JwaWinDLLNames.dcu
git rm --cached Composants/Librairies/jwa/Win32API/JwaWinNT.dcu
git rm --cached Composants/Librairies/jwa/Win32API/JwaWinSock.dcu
git rm --cached Composants/Librairies/jwa/Win32API/JwaWinSvc.dcu
git rm --cached Composants/Librairies/jwa/Win32API/JwaWinType.dcu
git rm --cached Modules/Commit/COMMIT.res
git rm --cached Modules/Commit/MSQL/MSQL.res
git rm --cached Modules/Commit/ModuleImport.res
git rm --cached Modules/Commit/ModuleTransfert/ModuleTransfert.res
git rm --cached Modules/Commit/Projet.res
git rm --cached Modules/Commit/etat_grille.res
git rm --cached Modules/Commit/rdm_commit.rc
git rm --cached Modules/Commit/rdm_commit.res
git rm --cached Modules/Commit/xml_rejets.res
git rm --cached Modules/Import/Actipharm/actipharm.res
git rm --cached Modules/Import/CIP/CIP.res
git rm --cached Modules/Import/DynaCaisse/DynaCaisse.res
git rm --cached Modules/Import/EsculapeV6/esculapev6.res
git rm --cached Modules/Import/FarmadTWin/FarmadTWin.res
git rm --cached Modules/Import/Greenock/Greenock.res
git rm --cached Modules/Import/ImportUltimate/ImportUltimate.res
git rm --cached Modules/Import/ImportUltimate/logo.res
git rm --cached Modules/Import/Infosoft/Infosoft.res
git rm --cached Modules/Import/Ipharma/IPharma.res
git rm --cached Modules/Import/Leo1/Leo1.res
git rm --cached Modules/Import/Leo1/logo.res
git rm --cached Modules/Import/Leo2/Leo2.res
git rm --cached Modules/Import/Leo2/logo.res
git rm --cached Modules/Import/Lgo2/Lgo2.res
git rm --cached Modules/Import/NEV/NEV.res
git rm --cached Modules/Import/NextPharm/NextPharm.res
git rm --cached Modules/Import/NextPharm/logo.res
git rm --cached Modules/Import/Officinall/logo.res
git rm --cached Modules/Import/Officinall/officinall.res
git rm --cached Modules/Import/Opus/Opus.res
git rm --cached Modules/Import/PharmaVitale/PharmaVitale.res
git rm --cached Modules/Import/PharmaVitale/logo.res
git rm --cached Modules/Import/Pharmony/Pharmony.res
git rm --cached Modules/Import/SmartRX/SmartRX.res
git rm --cached Modules/Import/Vindilis/Vindilis.res
git rm --cached Modules/Import/Vindilis/logo.res
git rm --cached Modules/Import/Winpharma/Winpharma.res
git rm --cached Modules/Import/Winpharma/logo.res
git rm --cached Modules/Import/XLSoft/XLSoft.res
git rm --cached Modules/Import/caducielv6/CaducielV6.rc
git rm --cached Modules/Import/caducielv6/CaducielV6.res
git rm --cached Modules/Import/importlgpi/importlgpi.res
git rm --cached Modules/Import/importlgpi/logo.res
git rm --cached Modules/Import/periphar/periphar.res
git rm --cached Modules/Import/pharmalandv7/pharmalandv7.res
git rm --cached Modules/Import/visiopharm/VisioPharm.res
git rm --cached Modules/Outils/OutilsERP_be/OutilsERP_be.res
git rm --cached Modules/Outils/OutilsERP_fr/OutilsERP_fr.res
git rm --cached Modules/Outils/OutilsPHA_fr/OutilsPHA_fr.res
git rm --cached Modules/Outils/Requeteur/Requeteur.res
git rm --cached Modules/Outils/Visualisation_be/Visualisation_be.res
git rm --cached Modules/Outils/Visualisation_fr/Visualisation_fr.res
git rm --cached Modules/Transfert/transfertlgpi/logo.res
git rm --cached Modules/Transfert/transfertlgpi/transfertlgpi.res
git rm --cached Modules/Transfert/transfertultimate/logo.res
git rm --cached Modules/Transfert/transfertultimate/transfertultimate.res
git rm --cached Outils/sauver_bd_sqls/sauver_bd_sqls.res
git rm --cached UDFs/ibfichier/ibfichier.res
git rm --cached UDFs/ibpha/ibpha.res
git rm --cached UDFs/ibstr/ibstr.res
git rm --cached UDFs/ibxml/ibxml.res