set sql dialect 3;

/* ********************************************************************************************** */
insert into t_fct_fichier(t_fct_fichier_id, nom, type_fichier, requis, libelle, commentaire, grille, ligne) values(next value for seq_fct_fichier, 'P01CONT.D', '10', '1', 'Contacts', 'Contacts', null, next value for seq_grille_imp_fichiers);
insert into t_fct_fichier(t_fct_fichier_id, nom, type_fichier, requis, libelle, commentaire, grille, ligne) values(next value for seq_fct_fichier, 'P01MEDE.D', '11', '1', 'Médecins', 'Médecins', 'grdPraticiens', next value for seq_grille_imp_praticiens);
insert into t_fct_fichier(t_fct_fichier_id, nom, type_fichier, requis, libelle, commentaire, grille, ligne) values(next value for seq_fct_fichier, 'P00SOC.D', '10', '1', 'Paramètres', 'Paramètres', null, next value for seq_grille_imp_fichiers);
insert into t_fct_fichier(t_fct_fichier_id, nom, type_fichier, requis, libelle, commentaire, grille, ligne) values(next value for seq_fct_fichier, 'P01FORM.D', '10', '1', 'Formules', 'Formules', null, next value for seq_grille_imp_fichiers);
insert into t_fct_fichier(t_fct_fichier_id, nom, type_fichier, requis, libelle, commentaire, grille, ligne) values(next value for seq_fct_fichier, 'P01OAMO.D', '11', '1', 'Organismes AMO', 'Organismes AMO', 'grdOrganismes', next value for seq_grille_imp_organismes);
insert into t_fct_fichier(t_fct_fichier_id, nom, type_fichier, requis, libelle, commentaire, grille, ligne) values(next value for seq_fct_fichier, 'P01OAMC.D', '11', '1', 'Organismes AMC', 'Organismes AMC', 'grdOrganismes', next value for seq_grille_imp_organismes);
insert into t_fct_fichier(t_fct_fichier_id, nom, type_fichier, requis, libelle, commentaire, grille, ligne) values(next value for seq_fct_fichier, 'P01CNTR.D', '11', '1', 'Contrats AMC', 'Contrats AMC', 'grdOrganismes', next value for seq_grille_imp_organismes);
insert into t_fct_fichier(t_fct_fichier_id, nom, type_fichier, requis, libelle, commentaire, grille, ligne) values(next value for seq_fct_fichier, 'P01TIER.D', '11', '1', 'Tiers', 'Tiers', 'grdAutresDonnees', next value for seq_grille_imp_autres_donnees);
insert into t_fct_fichier(t_fct_fichier_id, nom, type_fichier, requis, libelle, commentaire, grille, ligne) values(next value for seq_fct_fichier, 'P01ASSU.D', '11', '1', 'Assurés', 'Assurés', 'grdClients', next value for seq_grille_imp_clients);
insert into t_fct_fichier(t_fct_fichier_id, nom, type_fichier, requis, libelle, commentaire, grille, ligne) values(next value for seq_fct_fichier, 'P01AYDR.D', '11', '1', 'Bénéficaires', 'Bénéficaires', 'grdClients', next value for seq_grille_imp_clients);
insert into t_fct_fichier(t_fct_fichier_id, nom, type_fichier, requis, libelle, commentaire, grille, ligne) values(next value for seq_fct_fichier, 'P01FOUR.D', '11', '1', 'Fournisseurs', 'Fournisseurs', 'grdProduits', next value for seq_grille_imp_produits);
insert into t_fct_fichier(t_fct_fichier_id, nom, type_fichier, requis, libelle, commentaire, grille, ligne) values(next value for seq_fct_fichier, 'P01AYMU.D', '11', '1', 'Données AMC', 'Données AMC', 'grdClients', next value for seq_grille_imp_clients);
insert into t_fct_fichier(t_fct_fichier_id, nom, type_fichier, requis, libelle, commentaire, grille, ligne) values(next value for seq_fct_fichier, 'P01LPAR.D', '11', '1', 'Fabricants', 'Fabricants', 'grdProduits', next value for seq_grille_imp_produits);
insert into t_fct_fichier(t_fct_fichier_id, nom, type_fichier, requis, libelle, commentaire, grille, ligne) values(next value for seq_fct_fichier, 'P01EMPL.D', '11', '1', 'Emplacements', 'Emplacements', 'grdProduits', next value for seq_grille_imp_produits);
insert into t_fct_fichier(t_fct_fichier_id, nom, type_fichier, requis, libelle, commentaire, grille, ligne) values(next value for seq_fct_fichier, 'P01FAM.D', '11', '1', 'Familles', 'Familles', 'grdProduits', next value for seq_grille_imp_produits);
insert into t_fct_fichier(t_fct_fichier_id, nom, type_fichier, requis, libelle, commentaire, grille, ligne) values(next value for seq_fct_fichier, 'P01ARTI.D', '11', '1', 'Produits', 'Produits', 'grdProduits', next value for seq_grille_imp_produits);
insert into t_fct_fichier(t_fct_fichier_id, nom, type_fichier, requis, libelle, commentaire, grille, ligne) values(next value for seq_fct_fichier, 'M01DLOT.D', '11', '1', 'Informations de stocks', 'Informations de stocks', 'grdProduits', next value for seq_grille_imp_produits);
insert into t_fct_fichier(t_fct_fichier_id, nom, type_fichier, requis, libelle, commentaire, grille, ligne) values(next value for seq_fct_fichier, 'P01TARI.D', '11', '1', 'Tarifs', 'Tarifs', 'grdProduits', next value for seq_grille_imp_produits);
insert into t_fct_fichier(t_fct_fichier_id, nom, type_fichier, requis, libelle, commentaire, grille, ligne) values(next value for seq_fct_fichier, 'P01CUM.D', '11', '1', 'Historiques cumulés', 'Historiques cumulés', 'grdProduits', next value for seq_grille_imp_produits);
insert into t_fct_fichier(t_fct_fichier_id, nom, type_fichier, requis, libelle, commentaire, grille, ligne) values(next value for seq_fct_fichier, 'M01ENTE.D', '11', '1', 'Historiques délivrances entêtes', 'Historiques délivrances entêtes', 'grdAutresDonnees', next value for seq_grille_imp_autres_donnees);
insert into t_fct_fichier(t_fct_fichier_id, nom, type_fichier, requis, libelle, commentaire, grille, ligne) values(next value for seq_fct_fichier, 'M01LIGN.D', '11', '1', 'Historiques délivrances lignes', 'Historiques délivrances lignes', 'grdAutresDonnees', next value for seq_grille_imp_autres_donnees);

/* ********************************************************************************************** */
update t_cfg_prestation set utilisable_conversion = '0';
update t_cfg_prestation set utilisable_conversion = '1'  where t_ref_prestation_id in (select t_ref_prestation_id from t_ref_prestation where code in('PH1','PH2','PH4','PH7','PMR','AAD' ));
