set sql dialect 3;

/* ********************************************************************************************** */
insert into t_fct_fichier(t_fct_fichier_id, nom, type_fichier, requis, libelle, commentaire, grille, ligne) values(next value for seq_fct_fichier, 'MEDECINS.DBI', '11', '1', 'Médecins', 'Médecins', 'grdPraticiens', next value for seq_grille_imp_praticiens);
insert into t_fct_fichier(t_fct_fichier_id, nom, type_fichier, requis, libelle, commentaire, grille, ligne) values(next value for seq_fct_fichier, 'ORGANISM.DBI', '11', '1', 'Organismes', 'Organismes', 'grdOrganismes', next value for seq_grille_imp_organismes);
insert into t_fct_fichier(t_fct_fichier_id, nom, type_fichier, requis, libelle, commentaire, grille, ligne) values(next value for seq_fct_fichier, 'LIBCREMB.AMO', '11', '1', 'Remboursements AMO', 'Remboursements AMO', 'grdOrganismes', next value for seq_grille_imp_organismes);
insert into t_fct_fichier(t_fct_fichier_id, nom, type_fichier, requis, libelle, commentaire, grille, ligne) values(next value for seq_fct_fichier, 'CODEREMB.AMO', '11', '1', 'Taux de prise en charge AMO', 'Taux de prise en charge AMO', 'grdOrganismes', next value for seq_grille_imp_organismes);
insert into t_fct_fichier(t_fct_fichier_id, nom, type_fichier, requis, libelle, commentaire, grille, ligne) values(next value for seq_fct_fichier, 'LIBCREMB.AMC', '11', '1', 'Remboursements AMC', 'Remboursements AMC', 'grdOrganismes', next value for seq_grille_imp_organismes);
insert into t_fct_fichier(t_fct_fichier_id, nom, type_fichier, requis, libelle, commentaire, grille, ligne) values(next value for seq_fct_fichier, 'CODEREMB.AMC', '11', '1', 'Taux de prise en charge AMC', 'Taux de prise en charge AMC', 'grdOrganismes', next value for seq_grille_imp_organismes);
insert into t_fct_fichier(t_fct_fichier_id, nom, type_fichier, requis, libelle, commentaire, grille, ligne) values(next value for seq_fct_fichier, 'CODESITU.AMC', '10', '1', 'Codes situations AMC', 'Codes situations AMC', null, next value for seq_grille_imp_fichiers);
insert into t_fct_fichier(t_fct_fichier_id, nom, type_fichier, requis, libelle, commentaire, grille, ligne) values(next value for seq_fct_fichier, 'ASSURES.DBI', '11', '1', 'Assurés', 'Assurés', 'grdClients', next value for seq_grille_imp_clients);
insert into t_fct_fichier(t_fct_fichier_id, nom, type_fichier, requis, libelle, commentaire, grille, ligne) values(next value for seq_fct_fichier, 'LABFOUR.DBI', '11', '1', 'Fournisseurs', 'Fournisseurs', 'grdProduits', next value for seq_grille_imp_produits);
insert into t_fct_fichier(t_fct_fichier_id, nom, type_fichier, requis, libelle, commentaire, grille, ligne) values(next value for seq_fct_fichier, 'PRODUITS.DBI', '11', '1', 'Produits', 'Produits', 'grdProduits', next value for seq_grille_imp_produits);
insert into t_fct_fichier(t_fct_fichier_id, nom, type_fichier, requis, libelle, commentaire, grille, ligne) values(next value for seq_fct_fichier, 'MESSAGES.PDT', '11', '1', 'Commentaires Produits', 'Commentaire Produits', 'grdProduits', next value for seq_grille_imp_produits);
insert into t_fct_fichier(t_fct_fichier_id, nom, type_fichier, requis, libelle, commentaire, grille, ligne) values(next value for seq_fct_fichier, 'PERSONEL.IDX', '11', '1', 'Opérateurs', 'Opérateurs', 'grdEncours', next value for seq_grille_imp_encours);
insert into t_fct_fichier(t_fct_fichier_id, nom, type_fichier, requis, libelle, commentaire, grille, ligne) values(next value for seq_fct_fichier, 'CREDITS.DBI', '11', '1', 'Crédits', 'Crédits', 'grdEncours', next value for seq_grille_imp_encours);
insert into t_fct_fichier(t_fct_fichier_id, nom, type_fichier, requis, libelle, commentaire, grille, ligne) values(next value for seq_fct_fichier, 'AVANCESV.DBI', '11', '1', 'Avances Vignettes', 'Avances Vignettes', 'grdEncours', next value for seq_grille_imp_encours);
insert into t_fct_fichier(t_fct_fichier_id, nom, type_fichier, requis, libelle, commentaire, grille, ligne) values(next value for seq_fct_fichier, 'COMMANDE.*', '10', '1', 'Détails commandes en cours', 'Détails commandes', null, next value for seq_grille_imp_fichiers);
insert into t_fct_fichier(t_fct_fichier_id, nom, type_fichier, requis, libelle, commentaire, grille, ligne) values(next value for seq_fct_fichier, 'COMMANDE.LST', '11', '1', 'Entêtes commandes en cours', 'Entêtes commandes', 'grdEncours', next value for seq_grille_imp_encours);
insert into t_fct_fichier(t_fct_fichier_id, nom, type_fichier, requis, libelle, commentaire, grille, ligne) values(next value for seq_fct_fichier, 'HISTO.DBI', '11', '1', 'Historiques délivrances', 'Historiques délivrances', 'grdAutresDonnees', next value for seq_grille_imp_autres_donnees);
insert into t_fct_fichier(t_fct_fichier_id, nom, type_fichier, requis, libelle, commentaire, grille, ligne) values(next value for seq_fct_fichier, 'ARCH*.DBI', '10', '0', 'Documents', 'Documents', null, next value for seq_grille_imp_fichiers);
insert into t_fct_fichier(t_fct_fichier_id, nom, type_fichier, requis, libelle, commentaire, grille, ligne) values(next value for seq_fct_fichier, 'SCANS', '12', '1', 'Documents scannés', 'Documents scannés', 'grdAutresDonnees', next value for seq_grille_imp_autres_donnees);
insert into t_fct_fichier(t_fct_fichier_id, nom, type_fichier, requis, libelle, commentaire, grille, ligne) values(next value for seq_fct_fichier, 'SCANCLT.IDX', '11', '1', 'Lien documents - clients', 'Lien documents - clients', 'grdAutresDonnees', next value for seq_grille_imp_autres_donnees);

/* ********************************************************************************************** */
update t_cfg_prestation set utilisable_conversion = '0';
update t_cfg_prestation set utilisable_conversion = '1'  where t_ref_prestation_id in (select t_ref_prestation_id from t_ref_prestation where code in('PH1','PH2','PH4','PH7','PMR','AAD' ));
