create or replace package migration.pk_cartes_ristournes as

FUNCTION CreationCompte(
  ACOMPTE IN VARCHAR2,
  ACLIID IN NUMBER,
  ALIBERTYPE IN VARCHAR2,
  ALIBERVAL IN VARCHAR2,
  AETAT IN VARCHAR2,
  Aid_centralisation IN NUMBER,
  t_compte_id OUT NUMBER
 ) RETURN NUMBER;


FUNCTION CreationCarteRist(
  ACARTERIST IN VARCHAR2,
  ACOMPTEID IN NUMBER,
  ACLIID IN NUMBER,
  ADATEEMIS IN DATE,
  ANUMCARTE IN VARCHAR2,
  AVIRTUEL IN VARCHAR2,
  AETAT IN VARCHAR2,
  ASYNONYME IN VARCHAR2,
  ANUMAPBOFFICINE IN VARCHAR2,
  t_carterist_id OUT NUMBER
 ) RETURN NUMBER;


FUNCTION CreationTransactRist(
  ATRANSACTIONRIST IN VARCHAR2,
  ANUMCARTE IN VARCHAR2,
  ACOMPTEID IN NUMBER,
  AMONTANTRIST IN NUMBER,
  ATYPETRANSACT IN VARCHAR2,
  ATAUXTVA IN NUMBER,
  ATOTALTICKET IN NUMBER,
  AJUSTIFICATIF IN VARCHAR2,
  ADATETICKET IN DATE,
  t_transactrist_id OUT NUMBER
  ) RETURN NUMBER;

end;
/