SELECT 
  DET.MSD_ID,
  DET.MSD_CNKNUMMER AS CNK,
  SCH.MS_KLANT_ID AS CLIENT_ID,
  DET.MSD_BEGINDATUM AS DATE_DEB,
  DET.MSD_EINDDATUM AS DATE_FIN,
  FTBMSOPMERKINGEN.MSO_OPMERKING AS NOTE,
  FTBPOMSCHRIJVING.PT_OMSCHRIJVINGFR
FROM FTBMEDICATIESCHEMA SCH
inner JOIN FTBMSDETAILS DET ON (SCH.MS_ID = DET.MSD_SCHEMA_ID)
LEFT JOIN FTBMSOPMERKINGEN ON (DET.MSD_OPMERKING_ID = FTBMSOPMERKINGEN.MSO_ID)
LEFT JOIN FTBPOMSCHRIJVING ON (DET.MSD_CNKNUMMER = FTBPOMSCHRIJVING.PT_CNKNUMMER)
where SCH.MS_KLANT_ID is not null and DET.MSD_CNKNUMMER is not null
and DET.MSD_EINDDATUM IS NULL
