md tmp
copy MEDECIN.FIC .\tmp
copy MEDECIN.NDX .\tmp
copy MEDECIN.MMO .\tmp
copy CONCENTR.FIC .\tmp
copy CONCENTR.NDX .\tmp
copy CONCENTR.MMO .\tmp
copy ORGANISM.FIC .\tmp
copy ORGANISM.NDX .\tmp
copy ORGANISM.MMO .\tmp
copy MUTUELLE.FIC .\tmp
copy MUTUELLE.NDX .\tmp
copy MUTUELLE.MMO .\tmp
copy STATUT.FIC .\tmp
copy STATUT.NDX .\tmp
copy STATUT.MMO .\tmp
copy DROITAMO.FIC .\tmp
copy DROITAMO.NDX .\tmp
copy DROITAMO.MMO .\tmp
copy DROITCLI.FIC .\tmp
copy DROITCLI.NDX .\tmp
copy DROITCLI.MMO .\tmp
copy DROITAMC.FIC .\tmp
copy DROITAMC.NDX .\tmp
copy DROITAMC.MMO .\tmp
copy BENEFICE.FIC .\tmp
copy BENEFICE.NDX .\tmp
copy BENEFICE.MMO .\tmp
copy ASSURE.FIC .\tmp
copy ASSURE.NDX .\tmp
copy ASSURE.MMO .\tmp
copy REGROUP.FIC .\tmp
copy REGROUP.NDX .\tmp
copy REGROUP.MMO .\tmp
copy TVA.FIC .\tmp
copy TVA.NDX .\tmp
copy TVA.MMO .\tmp
copy REP.FIC .\tmp
copy REP.NDX .\tmp
copy REP.MMO .\tmp
copy LAB.FIC .\tmp
copy LAB.NDX .\tmp
copy LAB.MMO .\tmp
copy GROUPE.FIC .\tmp
copy GROUPE.NDX .\tmp
copy GROUPE.MMO .\tmp
copy ZONEGEO.FIC .\tmp
copy ZONEGEO.NDX .\tmp
copy ZONEGEO.MMO .\tmp
copy ARTICLE.FIC .\tmp
copy ARTICLE.NDX .\tmp
copy ARTICLE.MMO .\tmp
copy VENTE.FIC .\tmp
copy VENTE.NDX .\tmp
copy VENTE.MMO .\tmp
copy ARTLPP.FIC .\tmp
copy ARTLPP.NDX .\tmp
copy ARTLPP.MMO .\tmp
copy OPERATEU.FIC .\tmp
copy OPERATEU.NDX .\tmp
copy OPERATEU.MMO .\tmp
copy NOTEFAC.FIC .\tmp
copy NOTEFAC.NDX .\tmp
copy NOTEFAC.MMO .\tmp
copy LIGNEFAC.FIC .\tmpX
copy LIGNEFAC.NDX .\tmp
copy LIGNEFAC.MMO .\tmp
copy FAMILLE.FIC .\tmp
copy FAMILLE.NDX .\tmp
copy FAMILLE.MMO .\tmp
copy CREDIT.FIC .\tmp
copy CREDIT.NDX .\tmp
copy CREDIT.MMO .\tmp
copy LCREDIT.FIC .\tmp
copy LCREDIT.NDX .\tmp
copy LCREDIT.MMO .\tmp
copy DOCUMENT.FIC .\tmp
copy DOCUMENT.NDX .\tmp
copy DOCUMENT.MMO .\tmp
copy DOCPAGE.FIC .\tmp
copy DOCPAGE.NDX .\tmp
copy DOCPAGE.MMO .\tmp
copy COMLAB.FIC .\tmp
copy COMLAB.NDX .\tmp
copy COMLAB.MMO .\tmp
copy COMREP.FIC .\tmp
copy COMREP.NDX .\tmp
copy COMREP.MMO .\tmp
copy COMGRP.FIC .\tmp
copy COMGRP.NDX .\tmp
copy COMGRP.MMO .\tmp
copy ART_CODE13.FIC .\tmp
copy ART_CODE13.NDX .\tmp
copy ART_CODE13.MMO .\tmp
copy DOCPAGE.FIC .\tmp
copy DOCPAGE.NDX .\tmp
copy DOCPAGE.MMO .\tmp
copy PRIVILEG.FIC .\tmp
copy PRIVILEG.NDX .\tmp
copy PRIVILEG.MMO .\tmp
copy COMPROD.FIC .\tmp
copy COMPROD.NDX .\tmp
copy COMPROD.MMO .\tmp
copy COMARTIC.FIC .\tmp
copy COMARTIC.NDX .\tmp
copy COMARTIC.MMO .\tmp
copy COMECH.FIC .\tmp
copy COMECH.NDX .\tmp
copy COMECH.MMO .\tmp