select
ben.be_code,
ben.as_code,
trim(ben.as_nom) nom,
trim(ben.as_insee) insee,
trim(ben.as_cle) cle_insee,
trim(ben.be_nom) nom_ben,
trim(ben.be_preno) prenom_ben,
trim(ben.be_tel) telephone,
trim(ben.be_port) mobile,
trim(ben.be_dtnai) datenaiss,
trim(ben.be_gemel) rang,
trim(ben.be_admut),
trim(cast(be_dlim1 as varchar(10))),
trim(cast(be_dlim2 as varchar(10))),
trim(cast(be_dlimm as varchar(10))),
trim(ass.as_alert) commentaire_as,
trim(ben.be_obs) commentaire_ben,
trim(ben.be_ald) ald,
trim(ben.og_code),
trim(ben.og_num),
trim(ben.mu_code),
trim(ben.mu_num),
trim(ben.qu_code),
trim(ben.st_code1),
trim(ben.st_code2),
trim(cast(be_ddpas as varchar(10))),
trim(ben.be_rue) rue1,
trim(ben.be_rue2) rue2,
trim(ben.be_codpo) cp,
trim(ben.be_ville) ville,
trim(ben.be_fax) fax,
trim(ben.be_mail) mail,
trim(ben.ro_code)
from BENEFICE ben 
inner join ASSURE ass on ass.as_code = ben.as_code
