SELECT 
art.ar_cip,
trim(art.ar_cip13),
trim(art.ar_nom),
art.ar_pvent,
art.ar_ptips,
art.ar_sminc,
art.ar_stmax,
art.ar_stock,
art.ar_qtatd,
art.ar_caray,
art.ar_stoc2,
art.ar_phacg,
art.ar_phami,
art.ar_phare, 
trim(art.ac_code),
art.re_code,
tva.tv_taux,
trim(art.la_code),
art.fa_code,
trim(art.ta_code),
trim(art.zo_code),
trim(art.zo_cod2),
trim(art.ar_ctips),
trim(art.ar_ean13),
trim(art.ar_obs),
trim(art.ar_msgc),
art.ar_phafa,
trim(cast(art.ar_dtper as varchar(10))),
trim(art.ar_homeo),
trim(cast(art.ar_dasor as varchar(10))),
art.ar_pfcgd
FROM ARTICLE art
LEFT JOIN TVA ON tva.tv_code = art.tv_code 