set sql dialect 3;
/* Maj 04 2020 a partir de https://conventions.ubinect.fr/sp-sante/ */

insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '00401018','VERSPIEREN');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '00401026','GRAS SAVOYE');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '00401034','SOGAGIA');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '00401059','CGRM');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '00401067','ALP PREVOYANCE (ex COGEALP)');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '00401109','ONP CABINET FABIAN');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '00401125','HELIUM');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '00401141','FILHET-ALLARD & Cie');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '00401166','BALOO EX DELTA ASSURANCES');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '00401182','AON Hewitt (exAON CONSEIL)');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '00401216','CGAM');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '00401323','SGSanté ex:(AGEO ASSURANCES)');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '00401448','CPMS');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '00401455','DEDEYAN SANTE');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '00401471','BCAC');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '00401521','CABINET DIOT');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '00401547','STE FRANCAISE DE PREVENTION');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '00401554','GEREP');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '00401562','VIVINTER (ex PRC)');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '00401570','AREA Conseil');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '00401588','SOGAGIA');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '00401620','TELEGESTION');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '00401653','CETIM 2');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '00401679','BUREAU EUROPEEN DE PREVOYANCE');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '00401711','EPAI 2 M FINANCES');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '00401737','PLANSANTE');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '00401752','AIAC');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '00401760','GSP');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '00401794','DE CLARENS');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '00401802','R. DI GIOIA et CIE (exRDG Col)');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '00401836','AVILOG SOLUTIONS');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '00401885','ASSURASUD');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '00401943','CENTRE LORRAIN DE PREVOYANCE');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '00401968','ASCORE SAS');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '00402024','A.P.C.I.');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '00402040','LUXIOR ASSURANCES');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '00402065','GEISTEL');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '00402081','APRIA R.S.A.');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '00402107','CABINET MALMASSON');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '00402123','GROUPE TELERGOS');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '00402164','UGIPS GESTION');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '00402206','SLPA');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '00402297','CEGENORD');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '00402339','SACDROP ASSURANCES');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '00402370','APRIL ENTREPRISE CARAIBE ex: (');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '00402404','CABINET BOCQUET');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '00402412','U.C.R');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '00402453','APRIONIS Delegataire');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '00402487','STAM-EC');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '00402503','GIEPS');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '00402511','SOGAREP');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '00402529','KLESIA PREVOYANCE EX : APGME');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '00402545','CABINET PESENTI /APO');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '00402552','APO');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '00402602','SOLI-CAISSE');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '00402610','VIVENS Centre de Gestion');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '00402651','SASCO');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '00402677','UNIASSUR');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '00402685','PLANSANTE');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '00402701','DYNALIS EX SAPIA GESTION');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '00402727','GENASSUR');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '00402776','SQUADRA GESTION');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '00402784','INTER PREVOYANCE');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '00402792','D & O');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '00402826','HEMOS SANTE');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '00402875','GESTINEO');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '00402883','CETIM');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '00402925','COGEVIE');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '00402941','IGA GESTION');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '00402958','COLLECTEAM');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '00410001','ALLIANZ (ex AGF)');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '00420000','AXA');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '00440008','MMA Prestation Santé');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '00490003','AVIVA ASSURANCES');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '00490011','AMIS');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '02410017','AZUR ASSURANCES');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '02420008','MAPA');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '02420016','RCBF');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '02440014','LA MONDIALE');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '03430006','PACIFICA');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '03800000','NOVALIS PREVOYANCE');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '03800034','NOVALIS PLEIADE');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '04400008','MUTUELLE DE POITIERS ASSURANCE');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '04420006','AREAS ASSURANCES');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '05410006','LA MEDICALE DE FRANCE');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '07430002','THELEM ASSURANCES');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '08420002','GMF ASSURANCES');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '08460008','QUATREM ASSURANCES COLLECTIVES');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '08480006','CARMA');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '09420001','GROUPAMA');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '09470006','GAN');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '10410009','COVEA RISKS PRESTATION SANTE');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '10490001','KLESIA SA');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '11420007','Amaline-Amaguiz.com');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '34403336','KLESIA MUTUELLE EX:MORNAY MUTU');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '45239571','MUDIS');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '68119619','MUTA SANTE');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '75049595','MGAS');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '75947812','MUDOS');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '75950287','MUTUELLE GENERALE DE LA DISTRI');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '79003539','MAAF SANTE');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '93800019','APGIS');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '94860004','ARPEGE Prevoyance (ex CAIRPSA)');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '95800009','MV4 PRESTATIONS SANTE');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '95860003','APRIONIS');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '95890000','KLESIA PREVOYANCE (ex: IPGM)');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '96850011','REUNICA');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '97810006','CARCEPT');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '97890016','IPECA');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '98830003','AUDIENS PREVOYANCE');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '98870009','CAPAVES PREVOYANCE');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '99810012','TAITBOUT PREVOYANCE');
insert into t_ref_organisme (t_ref_organisme_id, type_organisme, identifiant_national, nom) values(next value for seq_ref_organisme,2, '99830002','CIRCO P');

commit;
