set sql dialect 3;

insert into t_ref_specialite (t_ref_specialite_id, code, libelle) values (next value for seq_ref_specialite,  '01', 'Omnipraticien-Médecine Générale');
insert into t_ref_specialite (t_ref_specialite_id, code, libelle) values (next value for seq_ref_specialite,  '02', 'Anesthesiste-Réanimation');
insert into t_ref_specialite (t_ref_specialite_id, code, libelle) values (next value for seq_ref_specialite,  '03', 'Cardiologie-Vasculaire');
insert into t_ref_specialite (t_ref_specialite_id, code, libelle) values (next value for seq_ref_specialite,  '04', 'Chirurgie Générale');
insert into t_ref_specialite (t_ref_specialite_id, code, libelle) values (next value for seq_ref_specialite,  '05', 'Dermato-Vénérologue');
insert into t_ref_specialite (t_ref_specialite_id, code, libelle) values (next value for seq_ref_specialite,  '06', 'Electroradiologie-Imagerie Médicale');
insert into t_ref_specialite (t_ref_specialite_id, code, libelle) values (next value for seq_ref_specialite,  '07', 'Gynécologie-Obstétrique');
insert into t_ref_specialite (t_ref_specialite_id, code, libelle) values (next value for seq_ref_specialite,  '08', 'Gastro-Entérologie Hépathologie');
insert into t_ref_specialite (t_ref_specialite_id, code, libelle) values (next value for seq_ref_specialite,  '09', 'Médecine Interne');
insert into t_ref_specialite (t_ref_specialite_id, code, libelle) values (next value for seq_ref_specialite,  '10', 'Neurochirurgie');
insert into t_ref_specialite (t_ref_specialite_id, code, libelle) values (next value for seq_ref_specialite,  '11', 'Oto-Rhino-Laryngologie');
insert into t_ref_specialite (t_ref_specialite_id, code, libelle) values (next value for seq_ref_specialite,  '12', 'Pédiatre');
insert into t_ref_specialite (t_ref_specialite_id, code, libelle) values (next value for seq_ref_specialite,  '13', 'Pneumologie');
insert into t_ref_specialite (t_ref_specialite_id, code, libelle) values (next value for seq_ref_specialite,  '14', 'Rhumatologie');
insert into t_ref_specialite (t_ref_specialite_id, code, libelle) values (next value for seq_ref_specialite,  '15', 'Ophtalmologie');
insert into t_ref_specialite (t_ref_specialite_id, code, libelle) values (next value for seq_ref_specialite,  '16', 'Chirurgie-Urologie');
insert into t_ref_specialite (t_ref_specialite_id, code, libelle) values (next value for seq_ref_specialite,  '17', 'Neuropsychiatrie');
insert into t_ref_specialite (t_ref_specialite_id, code, libelle) values (next value for seq_ref_specialite,  '18', 'Stomatologie');
insert into t_ref_specialite (t_ref_specialite_id, code, libelle) values (next value for seq_ref_specialite,  '19', 'Dentiste-Chirurgie-Dentaire');
insert into t_ref_specialite (t_ref_specialite_id, code, libelle) values (next value for seq_ref_specialite,  '20', 'Réanimation médicale');
insert into t_ref_specialite (t_ref_specialite_id, code, libelle) values (next value for seq_ref_specialite,  '21', 'Sage-Femme');
insert into t_ref_specialite (t_ref_specialite_id, code, libelle) values (next value for seq_ref_specialite,  '24', 'Infirmier(e)');
insert into t_ref_specialite (t_ref_specialite_id, code, libelle) values (next value for seq_ref_specialite,  '26', 'Masseur-Kinésithérapeute');
insert into t_ref_specialite (t_ref_specialite_id, code, libelle) values (next value for seq_ref_specialite,  '27', 'Pedicure-podologue');
insert into t_ref_specialite (t_ref_specialite_id, code, libelle) values (next value for seq_ref_specialite,  '28', 'Orthophoniste');
insert into t_ref_specialite (t_ref_specialite_id, code, libelle) values (next value for seq_ref_specialite,  '29', 'Orthoptiste');
insert into t_ref_specialite (t_ref_specialite_id, code, libelle) values (next value for seq_ref_specialite,  '30', 'Laboratoire Analyses Medicales');
insert into t_ref_specialite (t_ref_specialite_id, code, libelle) values (next value for seq_ref_specialite,  '31', 'Rééducation Réadaptation Fonctionnelle');
insert into t_ref_specialite (t_ref_specialite_id, code, libelle) values (next value for seq_ref_specialite,  '32', 'Neurologie');
insert into t_ref_specialite (t_ref_specialite_id, code, libelle) values (next value for seq_ref_specialite,  '33', 'Psychiatrie Générale');
insert into t_ref_specialite (t_ref_specialite_id, code, libelle) values (next value for seq_ref_specialite,  '34', 'Gériatrie');
insert into t_ref_specialite (t_ref_specialite_id, code, libelle) values (next value for seq_ref_specialite,  '35', 'Néphrologie');
insert into t_ref_specialite (t_ref_specialite_id, code, libelle) values (next value for seq_ref_specialite,  '36', 'Chirurgien dentiste spécialiste');
insert into t_ref_specialite (t_ref_specialite_id, code, libelle) values (next value for seq_ref_specialite,  '37', 'Anatomo-Cyto-Pathologie');
insert into t_ref_specialite (t_ref_specialite_id, code, libelle) values (next value for seq_ref_specialite,  '38', 'Directeur Médecin Biologiste ');
insert into t_ref_specialite (t_ref_specialite_id, code, libelle) values (next value for seq_ref_specialite,  '39', 'Laboratoire Analyse Biologie Médicale Polyvalent');
insert into t_ref_specialite (t_ref_specialite_id, code, libelle) values (next value for seq_ref_specialite,  '40', 'Laboratoire Analyse Biologie Cytologie-Pathologie');
insert into t_ref_specialite (t_ref_specialite_id, code, libelle) values (next value for seq_ref_specialite,  '41', 'Chirurgie Orthopédique-Traumatologie');
insert into t_ref_specialite (t_ref_specialite_id, code, libelle) values (next value for seq_ref_specialite,  '42', 'Endocrinologie Maladie Métaboliques');
insert into t_ref_specialite (t_ref_specialite_id, code, libelle) values (next value for seq_ref_specialite,  '43', 'Chirurgie infantile');
insert into t_ref_specialite (t_ref_specialite_id, code, libelle) values (next value for seq_ref_specialite,  '44', 'Chirurgie maxillo-faciale');
insert into t_ref_specialite (t_ref_specialite_id, code, libelle) values (next value for seq_ref_specialite,  '45', 'Chirurgie maxillo-faciale Stomatologie');
insert into t_ref_specialite (t_ref_specialite_id, code, libelle) values (next value for seq_ref_specialite,  '46', 'Chirurgie Plastique Esthétique');
insert into t_ref_specialite (t_ref_specialite_id, code, libelle) values (next value for seq_ref_specialite,  '47', 'Chirurgie Thoracique Cardiologie Vasculaire');
insert into t_ref_specialite (t_ref_specialite_id, code, libelle) values (next value for seq_ref_specialite,  '48', 'Chirurgie Vasculaire');
insert into t_ref_specialite (t_ref_specialite_id, code, libelle) values (next value for seq_ref_specialite,  '49', 'Chirurgie Viscérale et Digestive');
insert into t_ref_specialite (t_ref_specialite_id, code, libelle) values (next value for seq_ref_specialite,  '50', 'Pharmacien');
insert into t_ref_specialite (t_ref_specialite_id, code, libelle) values (next value for seq_ref_specialite,  '70', 'Gynécologie Médicale');
insert into t_ref_specialite (t_ref_specialite_id, code, libelle) values (next value for seq_ref_specialite,  '71', 'Hématologie');
insert into t_ref_specialite (t_ref_specialite_id, code, libelle) values (next value for seq_ref_specialite,  '72', 'Médecine Nucléaire');
insert into t_ref_specialite (t_ref_specialite_id, code, libelle) values (next value for seq_ref_specialite,  '73', 'Oncologie Médicale');
insert into t_ref_specialite (t_ref_specialite_id, code, libelle) values (next value for seq_ref_specialite,  '74', 'Oncologie Radiathérapique');
insert into t_ref_specialite (t_ref_specialite_id, code, libelle) values (next value for seq_ref_specialite,  '75', 'Psychiatrie Infantile');
insert into t_ref_specialite (t_ref_specialite_id, code, libelle) values (next value for seq_ref_specialite,  '76', 'Radiothérapie');
insert into t_ref_specialite (t_ref_specialite_id, code, libelle) values (next value for seq_ref_specialite,  '77', 'Obstétrique');
insert into t_ref_specialite (t_ref_specialite_id, code, libelle) values (next value for seq_ref_specialite,  '78', 'Génétique Médicale');
insert into t_ref_specialite (t_ref_specialite_id, code, libelle) values (next value for seq_ref_specialite,  '79', 'Gynécologie obstétrique et médicale');
insert into t_ref_specialite (t_ref_specialite_id, code, libelle) values (next value for seq_ref_specialite,  '80', 'Santé publique et médecine sociale');

commit;