set sql dialect 3;
-- maj 11 /2024 a partir de la vue migration.v_ref_organisme_amo

insert into t_ref_organisme values ( 1,'1',1,'011',null,null,'CPAM 011  BOURG EN BRESSE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2,'1',1,'021',null,null,'CPAM DE L''AISNE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 3,'1',1,'022',null,null,'CPAM 022  ST QUENTIN',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 4,'1',1,'031',null,null,'CPAM 031  MOULINS',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 5,'1',1,'041',null,null,'CPAM 041  DIGNE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 6,'1',1,'051',null,null,'CPAM 051  GAP',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 7,'1',1,'061',null,null,'CPAM 061  NICE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 8,'1',1,'071',null,null,'CPAM 071  ANNONAY',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 9,'1',1,'072',null,null,'CPAM DE L''ARDECHE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 10,'1',1,'081',null,null,'CPAM 081  CHARLEVILLE MEZIERES',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 11,'1',1,'091',null,null,'CPAM 091  FOIX',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 12,'1',1,'101',null,null,'CPAM 101  TROYES',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 13,'1',1,'111',null,null,'CPAM 111  CARCASSONNE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 14,'1',1,'121',null,null,'CPAM 121  RODEZ',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 15,'1',1,'131',null,null,'CPAM 131  MARSEILLE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 16,'1',1,'141',null,null,'CPAM 141  CAEN',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 17,'1',1,'151',null,null,'CPAM 151  AURILLAC',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 18,'1',1,'161',null,null,'CPAM 161  ANGOULEME',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 19,'1',1,'171',null,null,'CPAM 171  LA ROCHELLE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 20,'1',1,'181',null,null,'CPAM 181  BOURGES',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 21,'1',1,'191',null,null,'CPAM 191  TULLE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 22,'1',1,'201',null,null,'CPAM 201  AJACCIO',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 23,'1',1,'202',null,null,'CPAM 202  BASTIA',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 24,'1',1,'211',null,null,'CPAM 211  DIJON',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 25,'1',1,'221',null,null,'CPAM 221  ST BRIEUC',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 26,'1',1,'231',null,null,'CPAM 231  GUERET',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 27,'1',1,'241',null,null,'CPAM 241  PERIGUEUX',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 28,'1',1,'251',null,null,'CPAM DU DOUBS',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 29,'1',1,'252',null,null,'CPAM 252  MONTBELIARD',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 30,'1',1,'261',null,null,'CPAM 261  VALENCE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 31,'1',1,'271',null,null,'CPAM 271  EVREUX',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 32,'1',1,'281',null,null,'CPAM 281  CHARTRES',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 33,'1',1,'291',null,null,'CPAM DU FINISTERE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 34,'1',1,'292',null,null,'CPAM 292  QUIMPER',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 35,'1',1,'301',null,null,'CPAM 301  NIMES',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 36,'1',1,'311',null,null,'CPAM 311  TOULOUSE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 37,'1',1,'321',null,null,'CPAM 321  AUCH',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 38,'1',1,'331',null,null,'CPAM 331  BORDEAUX',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 39,'1',1,'341',null,null,'CPAM 341  BEZIERS',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 40,'1',1,'342',null,null,'CPAM DE L''HERAULT',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 42,'1',1,'351',null,null,'CPAM 351  RENNES',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 43,'1',1,'361',null,null,'CPAM 361  CHATEAUROUX',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 44,'1',1,'371',null,null,'CPAM 371  TOURS',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 45,'1',1,'381',null,null,'CPAM DE L''ISERE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 46,'1',1,'382',null,null,'CPAM 382  VIENNE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 47,'1',1,'391',null,null,'CPAM 391  LONS LE SAUNIER',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 48,'1',1,'401',null,null,'CPAM 401  MONT DE MARSAN',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 49,'1',1,'411',null,null,'CPAM 411 BLOIS',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 50,'1',1,'421',null,null,'CPAM 421  ROANNE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 51,'1',1,'422',null,null,'CPAM DE LA LOIRE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 52,'1',1,'431',null,null,'CPAM 431  LE PUY',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 53,'1',1,'441',null,null,'CPAM DE LOIRE ATLANTIQUE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 54,'1',1,'442',null,null,'CPAM 442  ST NAZAIRE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 55,'1',1,'451',null,null,'CPAM 451  ORLEANS',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 56,'1',1,'461',null,null,'CPAM 461  CAHORS',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 57,'1',1,'471',null,null,'CPAM 471  AGEN',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 58,'1',1,'481',null,null,'CPAM 481  MENDE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 59,'1',1,'491',null,null,'CPAM DE MAINE ET LOIRE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 60,'1',1,'492',null,null,'CPAM 492  CHOLET',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 61,'1',1,'501',null,null,'CPAM 501  ST LO',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 62,'1',1,'511',null,null,'CPAM 511  REIMS',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 63,'1',1,'521',null,null,'CPAM 521  CHAUMONT',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 64,'1',1,'531',null,null,'CPAM 531  LAVAL',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 65,'1',1,'541',null,null,'CPAM 541  LONGWY',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 66,'1',1,'542',null,null,'CPAM DE MEURTHE ET MOSELLE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 67,'1',1,'551',null,null,'CPAM 551  BAR LE DUC',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 68,'1',1,'561',null,null,'CPAM 561  VANNES',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 69,'1',1,'571',null,null,'CPAM DE MOSELLE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 70,'1',1,'572',null,null,'CPAM 572  SARREGUEMINES',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 71,'1',1,'573',null,null,'CPAM 573  THIONVILLE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 72,'1',1,'581',null,null,'CPAM 581  NEVERS',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 73,'1',1,'591',null,null,'CPAM 591  ARMENTIERES',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 74,'1',1,'592',null,null,'CPAM 592  CAMBRAI',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 75,'1',1,'593',null,null,'CPAM 593  DOUAI',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 76,'1',1,'594',null,null,'CPAM DES FLANDRES DUNKERQUE ARMENTIERES',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 77,'1',1,'595',null,null,'CPAM DE LILLE DOUAI',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 78,'1',1,'596',null,null,'CPAM 596  MAUBEUGE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 79,'1',1,'597',null,null,'CPAM DE ROUBAIX TOURCOING',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 80,'1',1,'598',null,null,'CPAM 598  TOURCOING',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 81,'1',1,'599',null,null,'CPAM DU HAINAUT',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 82,'1',1,'601',null,null,'CPAM DE L''OISE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 83,'1',1,'602',null,null,'CPAM 602  CREIL',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 84,'1',1,'611',null,null,'CPAM 611  ALENCON',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 85,'1',1,'621',null,null,'CPAM 621  ARRAS',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 86,'1',1,'622',null,null,'CPAM 622  BOULOGNE/MER',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 87,'1',1,'623',null,null,'CPAM DE LA COTE D''OPALE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 88,'1',1,'624',null,null,'CPAM DE L''ARTOIS',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 89,'1',1,'631',null,null,'CPAM 631  CLERMONT',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 90,'1',1,'641',null,null,'CPAM 641  BAYONNE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 91,'1',1,'642',null,null,'CPAM 642  PAU',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 92,'1',1,'651',null,null,'CPAM 651  TARBES',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 93,'1',1,'661',null,null,'CPAM 661  PERPIGNAN',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 94,'1',1,'671',null,null,'CPAM 671  HAGUENAU',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 95,'1',1,'672',null,null,'CPAM 672  SELESTAT',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 96,'1',1,'673',null,null,'CPAM DU BAS RHIN',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 97,'1',1,'681',null,null,'CPAM 681  COLMAR',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 98,'1',1,'682',null,null,'CPAM DU HAUT RHIN',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 99,'1',1,'691',null,null,'CPAM DU RHONE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 100,'1',1,'692',null,null,'CPAM 692  VILLEFRANCHE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 101,'1',1,'701',null,null,'CPAM 701  VESOUL',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 102,'1',1,'711',null,null,'CPAM 711  MACON',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 103,'1',1,'721',null,null,'CPAM 721  LE MANS',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 104,'1',1,'731',null,null,'CPAM 731  CHAMBERY',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 105,'1',1,'741',null,null,'CPAM 741  ANNECY',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 106,'1',1,'751',null,null,'CPAM 751  PARIS',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 107,'1',1,'761',null,null,'CPAM 761  DIEPPE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 108,'1',1,'762',null,null,'CPAM 762  ELBEUF',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 109,'1',1,'763',null,null,'CPAM 763  LE HAVRE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 110,'1',1,'764',null,null,'CPAM DE ROUEN ELBEUF DIEPPE SEINE MARITIME',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 111,'1',1,'771',null,null,'CPAM 771  MELUN RUBELLES',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 112,'1',1,'781',null,null,'CPAM 781  VERSAILLES',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 113,'1',1,'791',null,null,'CPAM 791  NIORT',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 114,'1',1,'801',null,null,'CPAM 801  AMIENS',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 115,'1',1,'811',null,null,'CPAM 811  ALBI',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 116,'1',1,'821',null,null,'CPAM 821  MONTAUBAN',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 117,'1',1,'831',null,null,'CPAM 831  TOULON',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 118,'1',1,'841',null,null,'CPAM 841  AVIGNON',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 119,'1',1,'851',null,null,'CPAM 851  LA ROCHE SUR YON',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 120,'1',1,'861',null,null,'CPAM 861  POITIERS',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 121,'1',1,'871',null,null,'CPAM 871  LIMOGES',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 122,'1',1,'881',null,null,'CPAM 881  EPINAL',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 123,'1',1,'891',null,null,'CPAM 891  AUXERRE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 124,'1',1,'901',null,null,'CPAM 901  BELFORT',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2235,'1',1,'909',null,null,'LMDE Assurance Maladie Etudiants',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 125,'1',1,'911',null,null,'CPAM 911  EVRY',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 126,'1',1,'921',null,null,'CPAM 921  NANTERRE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 127,'1',1,'931',null,null,'CPAM 931  BOBIGNY',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 128,'1',1,'941',null,null,'CPAM 941  CRETEIL',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 129,'1',1,'951',null,null,'CPAM 951  CERGY PONTOISE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 130,'1',1,'971',null,null,'CPAM 971  POINTE A PITRE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 131,'1',1,'972',null,null,'CPAM 972  FORT DE FRANCE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 132,'1',1,'973',null,null,'CPAM 973  CAYENNE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 133,'1',1,'974',null,null,'CPAM 974  SAINT DENIS',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2039,'1',1,'976',null,null,'CPAM 976  MAYOTTE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 134,'1',1,'999',null,null,'Contrat 1er euro',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 135,'1',2,'011',null,null,'MSA BOURG EN BRESSE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 136,'1',2,'015',null,null,'MSA BOURG EN BRESSE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 137,'1',2,'021',null,null,'MSA LAON',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 138,'1',2,'022',null,null,'GAMEX LAON',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 139,'1',2,'025',null,null,'MSA LAON',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 140,'1',2,'031',null,null,'MSA MOULINS',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 141,'1',2,'032',null,null,'GAMEX MOULINS',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 143,'1',2,'035',null,null,'MSA MOULINS',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 144,'1',2,'051',null,null,'MSA GAP',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 145,'1',2,'055',null,null,'MSA GAP',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 146,'1',2,'061',null,null,'MSA NICE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 147,'1',2,'065',null,null,'MSA NICE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 148,'1',2,'071',null,null,'MSA PRIVAS',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 149,'1',2,'075',null,null,'MSA PRIVAS',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 150,'1',2,'081',null,null,'MSA CHARLEVILLE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 151,'1',2,'085',null,null,'MSA CHARLEVILLE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 152,'1',2,'091',null,null,'MSA FOIX',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 153,'1',2,'095',null,null,'MSA FOIX',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 154,'1',2,'101',null,null,'MSA TROYES',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 155,'1',2,'102',null,null,'GAMEX TROYES',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 156,'1',2,'105',null,null,'MSA TROYES',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 157,'1',2,'111',null,null,'MSA CARCASSONNE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 158,'1',2,'115',null,null,'MSA CARCASSONNE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 159,'1',2,'121',null,null,'MSA RODEZ',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 160,'1',2,'122',null,null,'GAMEX RODEZ',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 161,'1',2,'125',null,null,'MSA RODEZ',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 162,'1',2,'131',null,null,'MSA MARSEILLE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 163,'1',2,'135',null,null,'MSA MARSEILLE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 164,'1',2,'141',null,null,'MSA CAEN',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 165,'1',2,'142',null,null,'GAMEX CAEN',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 166,'1',2,'145',null,null,'MSA CAEN',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 167,'1',2,'151',null,null,'MSA AURILLAC',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 168,'1',2,'155',null,null,'MSA AURILLAC',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 169,'1',2,'161',null,null,'MSA ANGOULEME',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 170,'1',2,'162',null,null,'GAMEX ANGOULEME',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 171,'1',2,'165',null,null,'MSA ANGOULEME',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 172,'1',2,'171',null,null,'MSA SAINTES',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 173,'1',2,'172',null,null,'GAMEX LA ROCHELLE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 174,'1',2,'175',null,null,'MSA SAINTES',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 175,'1',2,'181',null,null,'MSA BOURGES',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 176,'1',2,'182',null,null,'GAMEX BOURGES',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 177,'1',2,'185',null,null,'MSA BOURGES',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 178,'1',2,'191',null,null,'MSA TULLE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 179,'1',2,'195',null,null,'MSA TULLE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 180,'1',2,'201',null,null,'MSA AJACCIO',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 181,'1',2,'205',null,null,'MSA AJACCIO',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 182,'1',2,'211',null,null,'MSA DIJON',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 183,'1',2,'212',null,null,'GAMEX DIJON',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 184,'1',2,'215',null,null,'MSA DIJON',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 185,'1',2,'221',null,null,'MSA ST BRIEUC',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 186,'1',2,'222',null,null,'GAMEX ST BRIEUC',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 187,'1',2,'225',null,null,'MSA ST BRIEUC',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 188,'1',2,'231',null,null,'MSA GUERET',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 189,'1',2,'232',null,null,'GAMEX GUERET',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 190,'1',2,'235',null,null,'MSA GUERET',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 191,'1',2,'241',null,null,'MSA PERIGUEUX',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 192,'1',2,'242',null,null,'GAMEX PERIGUEUX',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 193,'1',2,'245',null,null,'MSA PERIGUEUX',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 194,'1',2,'251',null,null,'MSA BESANCON',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 195,'1',2,'252',null,null,'GAMEX BESANCON',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 196,'1',2,'255',null,null,'MSA BESANCON',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 197,'1',2,'261',null,null,'MSA VALENCE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 198,'1',2,'265',null,null,'MSA VALENCE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 199,'1',2,'271',null,null,'MSA EVREUX',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 200,'1',2,'272',null,null,'GAMEX EVREUX',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 201,'1',2,'275',null,null,'MSA EVREUX',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 202,'1',2,'281',null,null,'MSA CHARTRES',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 203,'1',2,'282',null,null,'GAMEX CHARTRES',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 204,'1',2,'285',null,null,'MSA CHARTRES',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 205,'1',2,'291',null,null,'MSA LANDERNEAU',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 206,'1',2,'292',null,null,'GAMEX BREST',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 207,'1',2,'295',null,null,'MSA LANDERNEAU',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 208,'1',2,'301',null,null,'MSA NIMES',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 209,'1',2,'305',null,null,'MSA NIMES',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 210,'1',2,'311',null,null,'MSA TOULOUSE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 211,'1',2,'312',null,null,'GAMEX TOULOUSE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 212,'1',2,'315',null,null,'MSA TOULOUSE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 213,'1',2,'321',null,null,'MSA AUCH',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 214,'1',2,'322',null,null,'GAMEX AUCH',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 215,'1',2,'325',null,null,'MSA AUCH',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 216,'1',2,'331',null,null,'MSA BORDEAUX',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 217,'1',2,'332',null,null,'GAMEX BORDEAUX',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 218,'1',2,'335',null,null,'MSA BORDEAUX',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 219,'1',2,'341',null,null,'MSA MONTPELLIER',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 220,'1',2,'342',null,null,'GAMEX MONTPELLIER',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 221,'1',2,'345',null,null,'MSA MONTPELLIER',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 224,'1',2,'351',null,null,'MSA RENNES',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 225,'1',2,'352',null,null,'GAMEX RENNES',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 226,'1',2,'355',null,null,'MSA RENNES',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 227,'1',2,'361',null,null,'MSA CHATEAUROUX',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 228,'1',2,'362',null,null,'GAMEX CHATEAUROUX',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 229,'1',2,'365',null,null,'MSA CHATEAUROUX',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 230,'1',2,'371',null,null,'MSA TOURS',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 231,'1',2,'372',null,null,'GAMEX TOURS',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 232,'1',2,'375',null,null,'MSA TOURS',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 233,'1',2,'381',null,null,'MSA GRENOBLE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 234,'1',2,'382',null,null,'GAMEX GRENOBLE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 235,'1',2,'385',null,null,'MSA GRENOBLE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 236,'1',2,'391',null,null,'MSA LONS LE SAUNIER',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 237,'1',2,'395',null,null,'MSA LONS LE SAUNIER',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 238,'1',2,'401',null,null,'MSA MONT DE MARSAN',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 239,'1',2,'405',null,null,'MSA MONT DE MARSAN',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 240,'1',2,'411',null,null,'MSA BLOIS',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 241,'1',2,'412',null,null,'GAMEX BLOIS',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 242,'1',2,'415',null,null,'MSA BLOIS',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 243,'1',2,'421',null,null,'MSA ST PRIEST EN JAREZ',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 244,'1',2,'425',null,null,'MSA ST PRIEST EN JAREZ',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 245,'1',2,'431',null,null,'MSA LE PUY',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 246,'1',2,'435',null,null,'MSA LE PUY',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 247,'1',2,'441',null,null,'MSA NANTES',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 248,'1',2,'442',null,null,'GAMEX NANTES',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 249,'1',2,'445',null,null,'MSA NANTES',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 250,'1',2,'451',null,null,'MSA ORLEANS',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 251,'1',2,'452',null,null,'GAMEX ORLEANS',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 252,'1',2,'455',null,null,'MSA ORLEANS',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 253,'1',2,'461',null,null,'MSA CAHORS',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 254,'1',2,'465',null,null,'MSA CAHORS',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 255,'1',2,'471',null,null,'MSA AGEN',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 256,'1',2,'472',null,null,'GAMEX AGEN',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 257,'1',2,'475',null,null,'MSA AGEN',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 258,'1',2,'481',null,null,'MSA MENDE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 259,'1',2,'485',null,null,'MSA MENDE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 260,'1',2,'491',null,null,'MSA ANGERS',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 261,'1',2,'492',null,null,'GAMEX ANGERS',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 262,'1',2,'495',null,null,'MSA ANGERS',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 263,'1',2,'501',null,null,'MSA ST LO',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 264,'1',2,'502',null,null,'GAMEX ST LO',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 266,'1',2,'505',null,null,'MSA ST LO',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 267,'1',2,'511',null,null,'MSA REIMS',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 268,'1',2,'512',null,null,'GAMEX CHALONS/MARNE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 269,'1',2,'515',null,null,'MSA REIMS',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 270,'1',2,'521',null,null,'MSA CHAUMONT',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 271,'1',2,'525',null,null,'MSA CHAUMONT',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 272,'1',2,'531',null,null,'MSA LAVAL',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 273,'1',2,'532',null,null,'GAMEX LAVAL',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 274,'1',2,'535',null,null,'MSA LAVAL',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 275,'1',2,'541',null,null,'MSA VANDOEUVRE LES NANCY',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 276,'1',2,'542',null,null,'GAMEX NANCY',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 277,'1',2,'545',null,null,'MSA VANDOEUVRE LES NANCY',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 278,'1',2,'551',null,null,'MSA VERDUN',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 279,'1',2,'555',null,null,'MSA VERDUN',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 280,'1',2,'561',null,null,'MSA VANNES',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 281,'1',2,'562',null,null,'GAMEX LORIENT',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 282,'1',2,'565',null,null,'MSA VANNES',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 283,'1',2,'571',null,null,'MSA METZ',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 284,'1',2,'575',null,null,'MSA METZ',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 285,'1',2,'581',null,null,'MSA NEVERS',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 286,'1',2,'582',null,null,'GAMEX NEVERS',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 287,'1',2,'585',null,null,'MSA NEVERS',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 288,'1',2,'591',null,null,'MSA LILLE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 289,'1',2,'592',null,null,'GAMEX LILLE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 290,'1',2,'595',null,null,'MSA LILLE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 291,'1',2,'601',null,null,'MSA BEAUVAIS',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 292,'1',2,'605',null,null,'MSA BEAUVAIS',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 293,'1',2,'611',null,null,'MSA ALENCON',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 294,'1',2,'612',null,null,'GAMEX ALENCON',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 295,'1',2,'615',null,null,'MSA ALENCON',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 296,'1',2,'621',null,null,'MSA ARRAS',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 297,'1',2,'622',null,null,'GAMEX ARRAS',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 298,'1',2,'625',null,null,'MSA ARRAS',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 299,'1',2,'631',null,null,'MSA CLERMONT FERRAND',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 300,'1',2,'632',null,null,'GAMEX CLERMONT FERRAND',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 301,'1',2,'635',null,null,'MSA CLERMONT FERRAND',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 302,'1',2,'641',null,null,'MSA PAU',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 303,'1',2,'642',null,null,'GAMEX PAU',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 304,'1',2,'645',null,null,'MSA PAU',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 305,'1',2,'651',null,null,'MSA TARBES',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 306,'1',2,'652',null,null,'GAMEX TARBES',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 307,'1',2,'655',null,null,'MSA TARBES',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 308,'1',2,'661',null,null,'MSA PERPIGNAN',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 309,'1',2,'662',null,null,'GAMEX PERPIGNAN',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 310,'1',2,'665',null,null,'MSA PERPIGNAN',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 311,'1',2,'671',null,null,'MSA STRASBOURG',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 312,'1',2,'672',null,null,'GAMEX STRASBOURG',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 313,'1',2,'675',null,null,'MSA STRASBOURG',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 314,'1',2,'681',null,null,'MSA COLMAR',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 315,'1',2,'685',null,null,'MSA COLMAR',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 316,'1',2,'691',null,null,'MSA LYON',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 317,'1',2,'692',null,null,'GAMEX LYON',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 318,'1',2,'695',null,null,'MSA LYON',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 319,'1',2,'701',null,null,'MSA VESOUL',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 320,'1',2,'705',null,null,'MSA VESOUL',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 321,'1',2,'711',null,null,'MSA MACON',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 322,'1',2,'712',null,null,'GAMEX MACON',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 323,'1',2,'715',null,null,'MSA MACON',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 324,'1',2,'721',null,null,'MSA LE MANS',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 325,'1',2,'722',null,null,'GAMEX LE MANS',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 326,'1',2,'725',null,null,'MSA LE MANS',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 327,'1',2,'731',null,null,'MSA CHAMBERY',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 328,'1',2,'735',null,null,'MSA CHAMBERY',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 329,'1',2,'741',null,null,'MSA ANNECY',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 330,'1',2,'745',null,null,'MSA ANNECY',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 331,'1',2,'751',null,null,'MSA PARIS',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1774,'1',2,'752',null,null,'AT AAEXA D.O.M-T.O.M (LANDERNEAU)',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 332,'1',2,'755',null,null,'MSA PARIS',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 333,'1',2,'761',null,null,'MSA BOIS GUILLAUME',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 334,'1',2,'762',null,null,'GAMEX ROUEN',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 335,'1',2,'765',null,null,'MSA BOIS GUILLAUME',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2236,'1',2,'771',null,null,'CPS ST BARTH',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2237,'1',2,'775',null,null,'CPS ST BARTH',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 336,'1',2,'791',null,null,'MSA NIORT',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 337,'1',2,'792',null,null,'GAMEX NIORT',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 338,'1',2,'795',null,null,'MSA NIORT',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 339,'1',2,'801',null,null,'MSA AMIENS',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 340,'1',2,'802',null,null,'GAMEX AMIENS',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 341,'1',2,'805',null,null,'MSA AMIENS',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 342,'1',2,'811',null,null,'MSA ALBI',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 343,'1',2,'812',null,null,'GAMEX ALBI',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 344,'1',2,'815',null,null,'MSA ALBI',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 345,'1',2,'821',null,null,'MSA MONTAUBAN',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 346,'1',2,'822',null,null,'GAMEX MONTAUBAN',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 347,'1',2,'825',null,null,'MSA MONTAUBAN',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 348,'1',2,'831',null,null,'MSA DRAGUIGNAN',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 349,'1',2,'832',null,null,'GAMEX TOULON',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 350,'1',2,'835',null,null,'MSA DRAGUIGNAN',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 351,'1',2,'841',null,null,'MSA AVIGNON',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 352,'1',2,'842',null,null,'GAMEX AVIGNON',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 353,'1',2,'845',null,null,'MSA AVIGNON',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 354,'1',2,'851',null,null,'MSA LA ROCHE S/YON',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 355,'1',2,'852',null,null,'GAMEX LA ROCHE S/YON',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 356,'1',2,'855',null,null,'MSA LA ROCHE S/YON',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 357,'1',2,'861',null,null,'MSA POITIERS',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 358,'1',2,'862',null,null,'GAMEX POITIERS',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 359,'1',2,'865',null,null,'MSA POITIERS',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 360,'1',2,'871',null,null,'MSA LIMOGES',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 361,'1',2,'872',null,null,'GAMEX LIMOGES',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 362,'1',2,'875',null,null,'MSA LIMOGES',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 363,'1',2,'881',null,null,'MSA EPINAL',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 364,'1',2,'885',null,null,'MSA EPINAL',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 365,'1',2,'891',null,null,'MSA AUXERRE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 366,'1',2,'892',null,null,'GAMEX AUXERRE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 367,'1',2,'895',null,null,'MSA AUXERRE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2162,'1',2,'941',null,null,'MSA D''ARMORIQUE - MAYOTTE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1772,'1',2,'962',null,null,'AT AAEXA LANDERNEAU',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 368,'1',2,'971',null,null,'MSA CGSS GUADELOUPE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1773,'1',2,'982',null,null,'AT AAEXA AURILLAC',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 369,'1',2,'992',null,null,'GAMEX AJACCIO',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 549,'1',4,'110','0000',null,'SNCF CAIS PREVOYANCE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 551,'1',4,'120','0000',null,'SNCF CAIS CADRES SUPERIEURS',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 553,'1',4,'220','0000',null,'SNCF CAIS MALADIE ALSACE LORRAINE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 555,'1',4,'400','0000',null,'SNCF REGIME DES SUBSISTANTS',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 557,'1',5,'051','0000',null,'RATP ASS MALADIE ACTIFS',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1840,'1',6,'200','0200',null,'ENIM - CLP BORDEAUX',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1842,'1',6,'200','0400',null,'ENIM - CLP SAINT MALO',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2238,'1',6,'200','0600',null,'ENIM',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1841,'1',6,'200','0800',null,'ENIM - CLP LORIENT',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 574,'1',7,'225',null,null,'REGIME MINIER DE SECURITE SOCIALE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 587,'1',8,'756','0100',null,'CNMSS Affilies',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 588,'1',8,'758','0200',null,'CNMSS Personnel',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2044,'1',8,'835','0300',null,'CNMSS Pensionnes Invalides de guerre',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 592,'1',10,'980','2101',null,'CRPCEN CLERCS NOTAIRE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 595,'1',12,'100','0000',null,'FONDS DE SECURITE SOCIALE ASSEMBLEE NATIONALE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 597,'1',13,'751','0000',null,'CAISSE DU SENAT',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2239,'1',15,'191','0000',null,'Caisse Francais Etranger',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1740,'1',16,'349','0000',null,'MINISTERE ANCIEN COMBATTANT',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 600,'1',17,'100','0000',null,'CAVIMAC DES CULTES',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1843,'1',17,'100','0011',null,'CAVIMAC DES CULTES',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 602,'1',18,'011','0506',null,'MGEN AIN',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 603,'1',18,'021','0506',null,'MGEN AISNE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 604,'1',18,'022','0506',null,'MGEN ST QUENTIN',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 605,'1',18,'031','0506',null,'MGEN ALLIER',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 606,'1',18,'041','0506',null,'MGEN ALPES DE HAUTE PROVENCE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 607,'1',18,'051','0506',null,'MGEN HAUTES ALPES',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 608,'1',18,'061','0506',null,'MGEN ALPES MARITIMES',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 609,'1',18,'071','0506',null,'MGEN ANNONAY',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 610,'1',18,'072','0506',null,'MGEN ARDECHE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 611,'1',18,'081','0506',null,'MGEN ARDENNES',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 612,'1',18,'091','0506',null,'MGEN ARIEGE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 613,'1',18,'101','0506',null,'MGEN AUBE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 614,'1',18,'111','0506',null,'MGEN AUDE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 615,'1',18,'121','0506',null,'MGEN AVEYRON',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 616,'1',18,'131','0506',null,'MGEN BOUCHES DU RHONE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 617,'1',18,'141','0506',null,'MGEN CALVADOS',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 618,'1',18,'151','0506',null,'MGEN CANTAL',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 619,'1',18,'161','0506',null,'MGEN CHARENTE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 620,'1',18,'171','0506',null,'MGEN CHARENTE MARITIME',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 621,'1',18,'181','0506',null,'MGEN CHER',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 622,'1',18,'191','0506',null,'MGEN CORREZE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 623,'1',18,'201','0506',null,'MGEN CORSE DU SUD',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 624,'1',18,'202','0506',null,'MGEN HAUTE CORSE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 625,'1',18,'211','0506',null,'MGEN COTE D''OR',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 626,'1',18,'221','0506',null,'MGEN COTES D''ARMOR',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 627,'1',18,'231','0506',null,'MGEN CREUSE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 628,'1',18,'241','0506',null,'MGEN DORDOGNE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 629,'1',18,'251','0506',null,'MGEN DOUBS',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 630,'1',18,'252','0506',null,'MGEN MONTBELIARD',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 631,'1',18,'261','0506',null,'MGEN DROME',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 632,'1',18,'271','0506',null,'MGEN EURE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 633,'1',18,'281','0506',null,'MGEN EURE ET LOIR',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 634,'1',18,'291','0506',null,'MGEN FINISTERE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 635,'1',18,'292','0506',null,'MGEN QUIMPER',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 636,'1',18,'301','0506',null,'MGEN GARD',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 637,'1',18,'311','0506',null,'MGEN HAUTE GARONNE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 638,'1',18,'321','0506',null,'MGEN GERS',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 639,'1',18,'331','0506',null,'MGEN GIRONDE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 640,'1',18,'341','0506',null,'MGEN BEZIERS',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 641,'1',18,'342','0506',null,'MGEN HERAULT',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 642,'1',18,'351','0506',null,'MGEN ILLE ET VILAINE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 643,'1',18,'361','0506',null,'MGEN INDRE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 644,'1',18,'371','0506',null,'MGEN INDRE ET LOIRE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 645,'1',18,'381','0506',null,'MGEN ISERE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 646,'1',18,'382','0506',null,'MGEN VIENNE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 647,'1',18,'391','0506',null,'MGEN JURA',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 648,'1',18,'401','0506',null,'MGEN LANDES',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 649,'1',18,'411','0506',null,'MGEN LOIR ET CHER',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 650,'1',18,'421','0506',null,'MGEN ROANNE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 651,'1',18,'422','0506',null,'MGEN LOIRE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 652,'1',18,'431','0506',null,'MGEN HAUTE LOIRE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 653,'1',18,'441','0506',null,'MGEN LOIRE ATLANTIQUE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 654,'1',18,'442','0506',null,'MGEN ST NAZAIRE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 655,'1',18,'451','0506',null,'MGEN LOIRET',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 656,'1',18,'461','0506',null,'MGEN LOT',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 657,'1',18,'471','0506',null,'MGEN LOT ET GARONNE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 658,'1',18,'481','0506',null,'MGEN LOZERE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 659,'1',18,'491','0506',null,'MGEN MAINE ET LOIRE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 660,'1',18,'492','0506',null,'MGEN CHOLET',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 661,'1',18,'501','0506',null,'MGEN MANCHE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 662,'1',18,'511','0506',null,'MGEN MARNE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 663,'1',18,'521','0506',null,'MGEN HAUTE MARNE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 664,'1',18,'531','0506',null,'MGEN MAYENNE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 665,'1',18,'541','0506',null,'MGEN LONGWY',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 666,'1',18,'542','0506',null,'MGEN MEURTHE ET MOSELLE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 667,'1',18,'551','0506',null,'MGEN MEUSE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 668,'1',18,'561','0506',null,'MGEN MORBIHAN',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 669,'1',18,'571','0506',null,'MGEN MOSELLE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 670,'1',18,'572','0506',null,'MGEN SARREGUEMINES',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 671,'1',18,'573','0506',null,'MGEN THIONVILLE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 672,'1',18,'581','0506',null,'MGEN NIEVRE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 673,'1',18,'591','0506',null,'MGEN ARMENTIERES',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 674,'1',18,'592','0506',null,'MGEN CAMBRAI',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 675,'1',18,'593','0506',null,'MGEN DOUAI',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 676,'1',18,'594','0506',null,'MGEN NORD 1',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 677,'1',18,'595','0506',null,'MGEN NORD 2',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 678,'1',18,'596','0506',null,'MGEN MAUBEUGE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 679,'1',18,'597','0506',null,'MGEN NORD 3',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 680,'1',18,'598','0506',null,'MGEN TOURCOING',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 681,'1',18,'599','0506',null,'MGEN NORD 4',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 682,'1',18,'601','0506',null,'MGEN OISE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 683,'1',18,'602','0506',null,'MGEN CREIL',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 684,'1',18,'611','0506',null,'MGEN ORNE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 685,'1',18,'621','0506',null,'MGEN ARRAS',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 686,'1',18,'622','0506',null,'MGEN BOULOGNE/MER',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 687,'1',18,'623','0506',null,'MGEN PAS DE CALAIS 1',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 688,'1',18,'624','0506',null,'MGEN PAS DE CALAIS  2',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 689,'1',18,'631','0506',null,'MGEN PUY DE DOME',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 690,'1',18,'641','0506',null,'MGEN PYRENEES ATLANTIQUES 1',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 691,'1',18,'642','0506',null,'MGEN PYRENEES ATLANTIQUES 2',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 692,'1',18,'651','0506',null,'MGEN HAUTES PYRENEES',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 693,'1',18,'661','0506',null,'MGEN PYRENEES ORIENTALES',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 694,'1',18,'671','0506',null,'MGEN HAGUENAU',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 695,'1',18,'672','0506',null,'MGEN SELESTAT',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 696,'1',18,'673','0506',null,'MGEN BAS RHIN',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 697,'1',18,'681','0506',null,'MGEN COLMAR',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 698,'1',18,'682','0506',null,'MGEN HAUT RHIN',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 699,'1',18,'691','0506',null,'MGEN RHONE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 700,'1',18,'692','0506',null,'MGEN VILLEFRANCHE/SAONE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 701,'1',18,'701','0506',null,'MGEN HAUTE SAONE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 702,'1',18,'711','0506',null,'MGEN SAONE ET LOIRE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 703,'1',18,'721','0506',null,'MGEN SARTHE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 704,'1',18,'731','0506',null,'MGEN SAVOIE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 705,'1',18,'741','0506',null,'MGEN HAUTE SAVOIE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 706,'1',18,'751','0501',null,'MGEN SEM ETRANGER',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 707,'1',18,'751','0506',null,'MGEN PARIS',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 708,'1',18,'761','0506',null,'MGEN DIEPPE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 709,'1',18,'762','0506',null,'MGEN ELBEUF',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 710,'1',18,'763','0506',null,'MGEN SEINE MARITIME 1',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 711,'1',18,'764','0506',null,'MGEN SEINE MARITIME 2',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 712,'1',18,'771','0506',null,'MGEN SEINE ET MARNE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 713,'1',18,'781','0506',null,'MGEN YVELINES',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 714,'1',18,'791','0506',null,'MGEN DEUX SEVRES',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 715,'1',18,'801','0506',null,'MGEN SOMME',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 716,'1',18,'811','0506',null,'MGEN TARN',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 717,'1',18,'821','0506',null,'MGEN TARN ET GARONNE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 718,'1',18,'831','0506',null,'MGEN  VAR',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 719,'1',18,'841','0506',null,'MGEN VAUCLUSE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 720,'1',18,'851','0506',null,'MGEN VENDEE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 721,'1',18,'861','0506',null,'MGEN VIENNE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 722,'1',18,'871','0506',null,'MGEN HAUTE VIENNE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 723,'1',18,'881','0506',null,'MGEN VOSGES',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 724,'1',18,'891','0506',null,'MGEN YONNE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 725,'1',18,'901','0506',null,'MGEN TERRITOIRE DE BELFORT',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 726,'1',18,'911','0506',null,'MGEN ESSONNE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 727,'1',18,'921','0506',null,'MGEN HAUTS DE SEINE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 728,'1',18,'931','0506',null,'MGEN SEINE SAINT DENIS',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 729,'1',18,'941','0506',null,'MGEN VAL DE MARNE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 730,'1',18,'951','0506',null,'MGEN VAL D''OISE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 731,'1',18,'971','0506',null,'MGEN GUADELOUPE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 732,'1',18,'972','0506',null,'MGEN MARTINIQUE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 733,'1',18,'973','0506',null,'MGEN GUYANE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 734,'1',18,'974','0506',null,'MGEN REUNION',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1869,'1',18,'976','0501',null,'MGEN MFP MAYOTTE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 743,'1',19,'072','0512',null,'LA MUTUELLE GENERALE ARDECHE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1945,'1',20,'789','0011',null,'MGP BOURG EN BRESSE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1946,'1',20,'789','0021',null,'MGP LAON',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1947,'1',20,'789','0022',null,'MGP SAINT QUENTIN',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1948,'1',20,'789','0031',null,'MGP MOULINS',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1949,'1',20,'789','0041',null,'MGP DIGNE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1950,'1',20,'789','0051',null,'MGP GAP',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1915,'1',20,'789','0061',null,'MGP NICE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1951,'1',20,'789','0071',null,'MGP ANNONAY',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1952,'1',20,'789','0072',null,'MGP PRIVAS',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1953,'1',20,'789','0081',null,'MGP CHARLEVILLE MEZIERES',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1954,'1',20,'789','0091',null,'MGP FOIX',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1955,'1',20,'789','0101',null,'MGP TROYES',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1916,'1',20,'789','0111',null,'MGP CARCASSONNE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1956,'1',20,'789','0121',null,'MGP RODEZ',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1917,'1',20,'789','0131',null,'MGP MARSEILLE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1957,'1',20,'789','0141',null,'MGP CAEN',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1918,'1',20,'789','0151',null,'MGP AURILLAC',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1958,'1',20,'789','0161',null,'MGP ANGOULEME',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1959,'1',20,'789','0171',null,'MGP LA ROCHELLE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1960,'1',20,'789','0181',null,'MGP BOURGES',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1961,'1',20,'789','0191',null,'MGP TULLE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1962,'1',20,'789','0201',null,'MGP AJACCIO',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1963,'1',20,'789','0202',null,'MGP BASTIA',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1887,'1',20,'789','0211',null,'MGP DIJON',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1964,'1',20,'789','0221',null,'MGP SAINT BRIEUC',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1965,'1',20,'789','0231',null,'MGP GUERET',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1890,'1',20,'789','0241',null,'MGP PERIGUEUX',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1968,'1',20,'789','0251',null,'MGP BESANCON',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1967,'1',20,'789','0252',null,'MGP MONTBELIARD',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1966,'1',20,'789','0261',null,'MGP VALENCE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1969,'1',20,'789','0271',null,'MGP EVREUX',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1970,'1',20,'789','0281',null,'MGP CHARTRES',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1919,'1',20,'789','0291',null,'MGP BREST',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1920,'1',20,'789','0292',null,'MGP QUIMPER',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1921,'1',20,'789','0301',null,'MGP NIMES',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1922,'1',20,'789','0311',null,'MGP TOULOUSE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1971,'1',20,'789','0321',null,'MGP AUCH',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1923,'1',20,'789','0331',null,'MGP BORDEAUX',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1924,'1',20,'789','0341',null,'MGP BEZIERS',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1925,'1',20,'789','0342',null,'MGP MONTPELLIER',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1972,'1',20,'789','0351',null,'MGP RENNES',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1973,'1',20,'789','0361',null,'MGP CHATEAUROUX',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1888,'1',20,'789','0371',null,'MGP TOURS',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1974,'1',20,'789','0381',null,'MGP GRENOBLE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1975,'1',20,'789','0382',null,'MGP VIENNE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1976,'1',20,'789','0391',null,'MGP LONS LE SAUNIER',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1977,'1',20,'789','0401',null,'MGP MONT DE MARSAN',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1978,'1',20,'789','0411',null,'MGP BLOIS',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1926,'1',20,'789','0421',null,'MGP ROANNE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1927,'1',20,'789','0422',null,'MGP SAINT ETIENNE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1979,'1',20,'789','0431',null,'MGP LE PUY',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1928,'1',20,'789','0441',null,'MGP NANTES',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1929,'1',20,'789','0442',null,'MGP SAINT NAZAIRE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1930,'1',20,'789','0451',null,'MGP ORLEANS',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1980,'1',20,'789','0461',null,'MGP CAHORS',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1891,'1',20,'789','0471',null,'MGP AGEN',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1981,'1',20,'789','0481',null,'MGP MENDE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1982,'1',20,'789','0491',null,'MGP ANGERS',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1983,'1',20,'789','0492',null,'MGP CHOLET',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1984,'1',20,'789','0501',null,'MGP SAINT LO',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1931,'1',20,'789','0511',null,'MGP REIMS',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1985,'1',20,'789','0521',null,'MGP CHAUMONT',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1986,'1',20,'789','0531',null,'MGP LAVAL',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2035,'1',20,'789','0541',null,'MGP LONGWY',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2036,'1',20,'789','0542',null,'MGP NANCY',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1987,'1',20,'789','0551',null,'MGP BAR LE DUC',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1932,'1',20,'789','0561',null,'MGP VANNES',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1933,'1',20,'789','0571',null,'MGP METZ',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1934,'1',20,'789','0572',null,'MGP SARREGUEMINES',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1935,'1',20,'789','0573',null,'MGP THIONVILLE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1988,'1',20,'789','0581',null,'MGP NEVERS',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1989,'1',20,'789','0591',null,'MGP ARMENTIERES',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1990,'1',20,'789','0592',null,'MGP CAMBRAI',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1991,'1',20,'789','0593',null,'MGP DOUAI',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1992,'1',20,'789','0594',null,'MGP DUNKERQUE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1993,'1',20,'789','0595',null,'MGP LILLE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1994,'1',20,'789','0596',null,'MGP MAUBEUGE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1995,'1',20,'789','0597',null,'MGP ROUBAIX',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1996,'1',20,'789','0598',null,'MGP TOURCOING',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1997,'1',20,'789','0599',null,'MGP VALENCIENNES',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1998,'1',20,'789','0601',null,'MGP BEAUVAIS',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1999,'1',20,'789','0602',null,'MGP CREIL',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2000,'1',20,'789','0611',null,'MGP ALENCON',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2001,'1',20,'789','0621',null,'MGP ARRAS',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2002,'1',20,'789','0622',null,'MGP BOULOGNE SUR MER',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2003,'1',20,'789','0623',null,'MGP CALAIS',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2004,'1',20,'789','0624',null,'MGP LENS',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1936,'1',20,'789','0631',null,'MGP CLERMONT FERRAND',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1937,'1',20,'789','0641',null,'MGP BAYONNE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1938,'1',20,'789','0642',null,'MGP PAU',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1943,'1',20,'789','0643',null,'MGP PAU MNH',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2005,'1',20,'789','0651',null,'MGP TARBES',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1939,'1',20,'789','0661',null,'MGP PERPIGNAN',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2006,'1',20,'789','0671',null,'MGP HAGUENAU',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2007,'1',20,'789','0672',null,'MGP SELESTAT',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2008,'1',20,'789','0673',null,'MGP STRASBOURG',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2009,'1',20,'789','0681',null,'MGP COLMAR',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2010,'1',20,'789','0682',null,'MGP MULHOUSE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2011,'1',20,'789','0691',null,'MGP LYON',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2012,'1',20,'789','0692',null,'MGP VILLEFRANCHE SUR SAONE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2013,'1',20,'789','0701',null,'MGP VESOUL',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2014,'1',20,'789','0711',null,'MGP MACON',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2015,'1',20,'789','0721',null,'MGP LE MANS',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2016,'1',20,'789','0731',null,'MGP CHAMBERY',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2017,'1',20,'789','0741',null,'MGP ANNECY',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1896,'1',20,'789','0751',null,'MGP UNG',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2018,'1',20,'789','0761',null,'MGP DIEPPE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2019,'1',20,'789','0762',null,'MGP ELBEUF',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2020,'1',20,'789','0763',null,'MGP LE HAVRE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2021,'1',20,'789','0764',null,'MGP ROUEN',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1895,'1',20,'789','0771',null,'MGP UNG',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1894,'1',20,'789','0781',null,'MGP UNG',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2022,'1',20,'789','0791',null,'MGP NIORT',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2023,'1',20,'789','0801',null,'MGP AMIENS',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2024,'1',20,'789','0811',null,'MGP ALBI',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2025,'1',20,'789','0821',null,'MGP MONTAUBAN',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1940,'1',20,'789','0831',null,'MGP TOULON',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2026,'1',20,'789','0841',null,'MGP AVIGNON',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2027,'1',20,'789','0851',null,'MGP LA ROCHE SUR YON',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2028,'1',20,'789','0861',null,'MGP POITIERS',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1941,'1',20,'789','0871',null,'MGP LIMOGES',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2029,'1',20,'789','0881',null,'MGP EPINAL',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1942,'1',20,'789','0891',null,'MGP AUXERRE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2030,'1',20,'789','0901',null,'MGP BELFORT',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1893,'1',20,'789','0911',null,'MGP UNG',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1892,'1',20,'789','0921',null,'MGP UNG',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1899,'1',20,'789','0931',null,'MGP UNG',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1898,'1',20,'789','0941',null,'MGP UNG',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1897,'1',20,'789','0951',null,'MGP UNG',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2031,'1',20,'789','0971',null,'MGP POINTE A PITRE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2032,'1',20,'789','0972',null,'MGP FORT DE FRANCE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2033,'1',20,'789','0973',null,'MGP CAYENNE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2034,'1',20,'789','0974',null,'MGP SAINT DENIS',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 926,'1',20,'974','0537',null,'MGP SAINT DENIS',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2054,'1',22,'459','0011',null,'MNH BOURG EN BRESSE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2055,'1',22,'459','0251',null,'MNH BESANCON',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2056,'1',22,'459','0281',null,'MNH CHARTRES 1',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2078,'1',22,'459','0282',null,'MNH CHARTRES 2',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2057,'1',22,'459','0291',null,'MNH BREST',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2058,'1',22,'459','0301',null,'MNH NIMES',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2059,'1',22,'459','0331',null,'MNH BORDEAUX',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2060,'1',22,'459','0371',null,'MNH TOURS',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2061,'1',22,'459','0381',null,'MNH GRENOBLE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2240,'1',22,'459','0444',null,'MNH',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2062,'1',22,'459','0451',null,'MNH ORLEANS',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2063,'1',22,'459','0471',null,'MNH AGEN',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2064,'1',22,'459','0542',null,'MNH NANCY',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2065,'1',22,'459','0711',null,'MNH MACON',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2066,'1',22,'459','0731',null,'MNH CHAMBERY',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2067,'1',22,'459','0751',null,'MNH PARIS',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2068,'1',22,'459','0781',null,'MNH VERSAILLES',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2074,'1',22,'459','0841',null,'MNH AVIGNON',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2075,'1',22,'459','0851',null,'MNH LA ROCHE SUR YON',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2076,'1',22,'459','0871',null,'MNH LIMOGES',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2077,'1',22,'459','0881',null,'MNH EPINAL',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2069,'1',22,'459','0911',null,'MNH EVRY',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2070,'1',22,'459','0921',null,'MNH NANTERRE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2071,'1',22,'459','0931',null,'MNH BOBIGNY',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2072,'1',22,'459','0941',null,'MNH CRETEIL',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2073,'1',22,'459','0951',null,'MNH PONTOISE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1312,'1',24,'331','0654',null,'MMC CONNEX',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2170,'1',24,'609','0021',null,'MUTUELLE INTERIALE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2169,'1',24,'609','0061',null,'MUTUELLE INTERIALE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2168,'1',24,'609','0131',null,'MUTUELLE INTERIALE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2154,'1',24,'609','0171',null,'MUTUELLE INTERIALE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2242,'1',24,'609','0241',null,'MUTUELLE INTERIALE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2158,'1',24,'609','0301',null,'MUTUELLE INTERIALE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2157,'1',24,'609','0311',null,'MUTUELLE INTERIALE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2149,'1',24,'609','0331',null,'MUTUELLE INTERIALE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2150,'1',24,'609','0342',null,'MUTUELLE INTERIALE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2151,'1',24,'609','0351',null,'MUTUELLE INTERIALE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2152,'1',24,'609','0441',null,'MUTUELLE INTERIALE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2167,'1',24,'609','0542',null,'MUTUELLE INTERIALE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2191,'1',24,'609','0571',null,'MUTUELLE INTERIALE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2190,'1',24,'609','0594',null,'MUTUELLE INTERIALE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2189,'1',24,'609','0595',null,'MUTUELLE INTERIALE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2188,'1',24,'609','0597',null,'MUTUELLE INTERIALE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2187,'1',24,'609','0599',null,'MUTUELLE INTERIALE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2186,'1',24,'609','0602',null,'MUTUELLE INTERIALE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2185,'1',24,'609','0623',null,'MUTUELLE INTERIALE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2184,'1',24,'609','0624',null,'MUTUELLE INTERIALE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2155,'1',24,'609','0641',null,'MUTUELLE INTERIALE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2156,'1',24,'609','0642',null,'MUTUELLE INTERIALE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2183,'1',24,'609','0691',null,'MUTUELLE INTERIALE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2182,'1',24,'609','0751',null,'MUTUELLE INTERIALE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2181,'1',24,'609','0763',null,'MUTUELLE INTERIALE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2180,'1',24,'609','0764',null,'MUTUELLE INTERIALE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2179,'1',24,'609','0771',null,'MUTUELLE INTERIALE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2178,'1',24,'609','0781',null,'MUTUELLE INTERIALE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2177,'1',24,'609','0801',null,'MUTUELLE INTERIALE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2176,'1',24,'609','0831',null,'MUTUELLE INTERIALE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2175,'1',24,'609','0911',null,'MUTUELLE INTERIALE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2174,'1',24,'609','0921',null,'MUTUELLE INTERIALE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2173,'1',24,'609','0931',null,'MUTUELLE INTERIALE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2172,'1',24,'609','0941',null,'MUTUELLE INTERIALE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2171,'1',24,'609','0951',null,'MUTUELLE INTERIALE',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1480,'1',24,'673','0689',null,'MUTUELLE DE L EST',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2165,'1',24,'691','0505',null,'MAGE LYON',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1516,'1',24,'751','0505',null,'MAGE PARIS',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2241,'1',24,'751','0533',null,'MUT AFFAIRES ETRANGERES EUROPEENNES',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1519,'1',24,'751','0602',null,'MCVPAP PARIS (75)',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1550,'1',24,'781','0602',null,'MCVPAP PARIS (78)',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1591,'1',24,'911','0602',null,'MCVPAP PARIS (91)',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1598,'1',24,'921','0602',null,'MCVPAP PARIS (92)',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1609,'1',24,'931','0602',null,'MCVPAP PARIS (93)',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1864,'1',24,'939','0603',null,'CAMIEG',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1617,'1',24,'941','0602',null,'MCVPAP PARIS (94)',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 1624,'1',24,'951','0602',null,'MCVPAP PARIS (95)',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2244,'1',25,'981','0000',null,'CCSS MONACO',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2245,'1',25,'982','0000',null,'SPME MONACO',null,null,null,null,null,null,null);
insert into t_ref_organisme values ( 2243,'1',25,'983','0000',null,'CAMTI MONACO',null,null,null,null,null,null,null);


ALTER SEQUENCE seq_ref_organisme RESTART WITH 4000;	