insert into t_ref_formule values(next value for seq_ref_formule, '% TR - MRO', '02A', 'Min(DR-MRO, %TR-MRO)');
insert into t_ref_formule values(next value for seq_ref_formule, '100% TM', '052', 'Min(DR-MRO, %TM)');
insert into t_ref_formule values(next value for seq_ref_formule, 'Frais réels', '010', 'Min(DR-MRO, DR)');
insert into t_ref_formule values(next value for seq_ref_formule, '% TM', '050', 'Min(DR-MRO, %TM)');
insert into t_ref_formule values(next value for seq_ref_formule, 'Frais réels plafonnés', '011', 'Min(DR-MRO, plafond, DR)');
insert into t_ref_formule values(next value for seq_ref_formule, '% DR', '012', 'Min(DR-MRO, %DR)');
insert into t_ref_formule values(next value for seq_ref_formule, '% DR plafonné', '013', 'Min(DR-MRO, plafond, %DR)');
insert into t_ref_formule values(next value for seq_ref_formule, '% DR - Montant RO, le tout plafonné', '014', 'Min(DR-MRO, plafond, %DR-MRO)');
insert into t_ref_formule values(next value for seq_ref_formule, '100% TR ou 100% de la Base Sécu', '020', 'Min(DR-MRO, %TR)');
insert into t_ref_formule values(next value for seq_ref_formule, '% TR', '021', 'Min(DR-MRO, %TR)');
insert into t_ref_formule values(next value for seq_ref_formule, '% TR plafonné', '022', 'Min(DR-MRO, plafond, %TR)');
insert into t_ref_formule values(next value for seq_ref_formule, '% TR + montant forfaitaire', '023', 'Min(DR-MRO, %TR+forfait)');
insert into t_ref_formule values(next value for seq_ref_formule, '% TR + montant forfaitaire, le tout plafonné', '024', 'Min(DR-MRO, plafond, %TR+forfait)');
insert into t_ref_formule values(next value for seq_ref_formule, '% TR - MRO + montant forfaitaire', '025', 'Min(DR-MRO, %TR-MRO+forfait)');
insert into t_ref_formule values(next value for seq_ref_formule, '% TR - MRO + montant forfaitaire, le tout plafonné', '026', 'Min(DR-MRO, plafond, %TR-MRO+forfait)');
insert into t_ref_formule values(next value for seq_ref_formule, '% TR + MRO + montant forfaitaire', '027', 'Min(DR-MRO, %TR+MRO+forfait)');
insert into t_ref_formule values(next value for seq_ref_formule, '% TR + MRO + montant forfaitaire, le tout plafonné', '028', 'Min(DR-MRO, plafond, %TR+MRO+forfait)');
insert into t_ref_formule values(next value for seq_ref_formule, '100% TR - MRO', '029', 'Min(DR-MRO, %TR-MRO)');
insert into t_ref_formule values(next value for seq_ref_formule, '% MRO + montant forfaitaire', '030', 'Min(DR-MRO, %MRO+forfait)');
insert into t_ref_formule values(next value for seq_ref_formule, '% MRO + montant forfaitaire, le tout plafonné', '031', 'Min(DR-MRO, plafond, %MRO+forfait)');
insert into t_ref_formule values(next value for seq_ref_formule, '% PMSS', '040', 'Min(DR-MRO, %PMSS)');
insert into t_ref_formule values(next value for seq_ref_formule, '% PMSS plafonné', '041', 'Min(DR-MRO, plafond, %PMSS)');
insert into t_ref_formule values(next value for seq_ref_formule, '% PMSS - MRO', '042', 'Min(DR-MRO, %PMSS-MRO)');
insert into t_ref_formule values(next value for seq_ref_formule, '% PMSS - MRO, le tout plafonné', '043', 'Min(DR-MRO, plafond, %PMSS-MRO)');
insert into t_ref_formule values(next value for seq_ref_formule, '% TM plafonné', '051', 'Min(DR-MRO, plafond, %TM)');
insert into t_ref_formule values(next value for seq_ref_formule, '% TC', '060', 'Min(DR-MRO, %TC théorique)');
insert into t_ref_formule values(next value for seq_ref_formule, '% TC plafonné', '061', 'Min(DR-MRO, plafond, %TC théorique)');
insert into t_ref_formule values(next value for seq_ref_formule, 'Formule générique', '090', 'Min(DR-MRO, plafond, %DR+%TR+%MRO+%PMSS+%TM+forfait+%TC théorique)');